// Tim Buckwheat's one-off briefing for an invasion that runs on a rule the
// battlefield never states out loud.
//
// The Pirates are the case this exists for. Their Scallywag throws its own dex clock
// away and MIRRORS whatever attack cycle the zombie in front of it has
// (BattleSim.cycleMs → mirroredAttackIntervalSec), so bringing a fast army just hands
// the pirates the same speed back. The shipped game states this exactly once, in raid
// 3's `failureText` — "Rumors say pirates clobber anything that moves too fast" — which
// the player only reads after the lesson has already cost them a fight and a squad.
// Tim says it up front instead, keeping the game's own wording.
//
// Deliberately NOT in raids.json: that file is generated by tools/prep_raids.py, so a
// hand-added field there is reverted by the next prep run.

/** Keyed by raid id. One tip per raid; shown once per device (see prefs.hasSeenRaidTip). */
export const RAID_TIPS: Record<number, string> = {
  3: "Rumors say pirates clobber anything that moves too fast. hmmmm...",
  // The Mega-Robot (BattleSim.stepMegaBot). The shared hazard tip is once-ever and a
  // player reaching Robots at L31 has long since spent it on the Ninjas' carrot wall,
  // so this one rides the per-raid slot instead.
  5: "Watch the background! Them robots built a MEGA-ROBOT that looks just like ol' me.\n" +
    "When its eyes start glowin', tap 'em quick to shut it down —\n" +
    "or it'll blast yer zombies with nuclear flames!",
};

/** Tim's briefing for this invasion, or null if it has nothing to warn about. */
export function raidTip(raidId: number): string | null {
  return RAID_TIPS[raidId] ?? null;
}
