// GENERATED by tools/freeze_effective.mjs — do not edit by hand.
//
// The effective-strength fit, frozen. Regenerate with:
//   npm run test:effective && node tools/freeze_effective.mjs
//
// Measured over 2500 uniformly random sixteen-zombie armies flown against a
// six-fight battery at expert play (src/raid/harness/effectiveStrength.ts). On 500
// held-out armies these weights order results at Spearman 0.7783, against the
// Strength Ladder's 0.1517 — the old metric is not weak, it is
// ANTI-correlated with winning.
//
// Values are on the Strength Ladder's numeric range so the two can be read side by side.
// Only DIFFERENCES are meaningful: every army has sixteen slots, so the counts sum to a
// constant and a shared offset predicts identically.

/** Per-species, for the 86 species actually sampled (the level-50 shortlist). */
export const EFFECTIVE_WEIGHT: Readonly<Record<string, number>> = {
  ZombieActorOmegaDrZombie: 57.9655, // Garden · ladder 31.5238
  ZombieActorDrZombie: 54.4661, // Garden · ladder 27.1882
  ZombieActorGardenTier6: 49.5501, // Garden · ladder 25.923
  ZombieActorZombug: 49.0016, // Small · ladder 39.6863
  ZombieActorProto: 46.0635, // Small · ladder 28.9828
  ZombieActorGardenTier5: 39.1077, // Garden · ladder 8.556
  ZombieActorGardenTier4: 38.9231, // Garden · ladder 7.7782
  ZombieActorGardenTier3: 37.4579, // Garden · ladder 5.6569
  ZombieActorRegularFinalBoss: 36.3301, // Regular · ladder 51.9875
  ZombieActorMerZombie: 35.9422, // Large · ladder 33.4664
  ZombieActorRegularVideoGame: 34.8149, // Regular · ladder 46.2817
  ZombieActorMadame: 34.1357, // Female · ladder 55.1362
  ZombieActorPoseidon: 34.1078, // Large · ladder 40.2492
  ZombieActorZombieBot: 32.5499, // Headless · ladder 27.9106
  ZombieActorOmegaZombieBot: 32.2087, // Headless · ladder 31.8119
  ZombieActorVagabond: 31.4942, // Regular · ladder 57.9655
  ZombieActorDiva: 31.0454, // Female · ladder 51.3809
  ZombieActorLargeTier6: 30.786, // Large · ladder 24.1868
  ZombieActorHeadlessTier6: 29.4461, // Headless · ladder 20.3101
  ZombieActorZomtar: 29.2489, // Regular · ladder 48.4355
  ZombieActorHeadlessTier4: 29.207, // Headless · ladder 16.4317
  ZombieActorCaptain: 29.0906, // Regular · ladder 40.8271
  ZombieActorLargeTier4: 28.2862, // Large · ladder 20.3322
  ZombieActorHeadless2Tier5: 28.0747, // Headless · ladder 22.9565
  ZombieActorAdmiral: 28.0698, // Regular · ladder 46.2623
  ZombieActorLargeTier5: 28.0098, // Large · ladder 22.3655
  ZombieActorBombie: 27.991, // Headless · ladder 18.0748
  ZombieActorBandido: 27.9137, // Regular · ladder 51.5752
  ZombieActorBrockColey: 27.575, // Regular · ladder 33.2265
  ZombieActorScrooge: 27.3338, // Regular · ladder 50.5964
  ZombieActorZosmonaut: 27.1905, // Regular · ladder 51.1896
  ZombieActorRegularTier6: 26.1371, // Regular · ladder 34.641
  ZombieActorChristmasGhost: 25.8238, // Regular · ladder 44.7214
  ZombieActorSheriff: 25.8182, // Regular · ladder 34.99
  ZombieActorHeadlessTier5: 25.1116, // Headless · ladder 18.0748
  ZombieActorMasterNinjombie: 23.8154, // Regular · ladder 45.2548
  ZombieActorForest: 23.4778, // Female · ladder 22.2587
  ZombieActorGardenTier2: 23.4046, // Garden · ladder 3.5355
  ZombieActorZomdini: 23.0641, // Regular · ladder 40.8167
  ZombieActorZastronaut: 22.9893, // Regular · ladder 45.7373
  ZombieActorDeputy: 22.0407, // Regular · ladder 28.5692
  ZombieActorDapper: 22.0145, // Large · ladder 22.3655
  ZombieActorSmallTier6: 21.2549, // Small · ladder 21.4942
  ZombieActorLargeTier3: 20.9439, // Large · ladder 15.1545
  ZombieActorNinjombie: 20.7879, // Regular · ladder 38.2426
  ZombieActorGirlTier6: 20.3463, // Female · ladder 24.6247
  ZombieActorGardenTier1: 19.0953, // Garden · ladder 1.4142
  ZombieActorRegularTier5: 18.8481, // Regular · ladder 22.889
  ZombieActorRegularTier4Eyebiscus: 18.7793, // Regular · ladder 20.7846
  ZombieActorGirlTier4: 18.7609, // Female · ladder 19.4332
  ZombieActorZombozo: 18.7076, // Small · ladder 18.9737
  ZombieActorSmallTier3: 18.6359, // Small · ladder 9.4868
  ZombieActorHeadlessTier3: 18.6274, // Headless · ladder 11.3137
  ZombieActorGirlTier5: 18.4469, // Female · ladder 21.3801
  ZombieActorSmallTier5: 18.2675, // Small · ladder 17.0411
  ZombieActorRegular4Tier5: 18.1857, // Regular · ladder 21.8815
  ZombieActorRegularTier4Heartichoke: 17.3362, // Regular · ladder 20.7846
  ZombieActorRegularTier4: 16.425, // Regular · ladder 20.7846
  ZombieActorHeadlessTier2: 15.9881, // Headless · ladder 5.7446
  ZombieActorRegularTier3DragonFruit: 15.9028, // Regular · ladder 12.6491
  ZombieActorGranny: 14.4875, // Female · ladder 21.3801
  ZombieActorRegularTier3: 14.4353, // Regular · ladder 12.6491
  ZombieActorSmallTier4: 14.1829, // Small · ladder 15.4919
  ZombieActorLargeTier2: 14.0606, // Large · ladder 8.45
  ZombieActorSmallTier1: 12.9216, // Small · ladder 2.4495
  ZombieActorGirlTier3: 11.8846, // Female · ladder 11.7505
  ZombieActorRegularTier3VenusFlytrap: 11.8386, // Regular · ladder 12.6491
  ZombieActorRegularTier2Cauliflower: 11.158, // Regular · ladder 7.0711
  ZombieActorRegularTier2LimaBeans: 11.0803, // Regular · ladder 7.0711
  ZombieActorOldMcZombie: 10.4457, // Regular · ladder 18.7702
  ZombieActorRegularTier1Tomatoes: 9.9981, // Regular · ladder 2.8284
  ZombieActorLargeTier1: 9.7448, // Large · ladder 3.6074
  ZombieActorSmallTier2: 9.2952, // Small · ladder 5.8583
  ZombieActorRegularTier2Garlic: 9.0296, // Regular · ladder 7.0711
  ZombieActorRegularTier2Broccoli: 8.2452, // Regular · ladder 7.0711
  ZombieActorHeadlessTier1: 8.1607, // Headless · ladder 2.6833
  ZombieActorGirlTier2: 7.1301, // Female · ladder 6.4537
  ZombieActorRegularTier2: 6.6525, // Regular · ladder 7.0711
  ZombieActorRegularTier1Coffee: 6.5931, // Regular · ladder 2.8284
  ZombieActorRegularTier2Celery: 6.2472, // Regular · ladder 7.0711
  ZombieActorRegularTier1Turnips: 5.7032, // Regular · ladder 2.8284
  ZombieActorGirlTier1: 5.1129, // Female · ladder 2.8062
  ZombieActorRegularTier1: 3.8624, // Regular · ladder 2.8284
  ZombieActorRegularTier1Potatoes: 3.6362, // Regular · ladder 2.8284
  ZombieActorRegularTier1Onions: 3.4639, // Regular · ladder 2.8284
  ZombieActorRegularTier1Carrots: 2.5836, // Regular · ladder 2.8284
};

/** Mean effective value of a class, for species the sample never contained. */
export const CLASS_EFFECTIVE: Readonly<Record<string, number>> = {
  Female: 18.4828,
  Garden: 39.9963,
  Headless: 24.7365,
  Large: 24.8773,
  Regular: 17.9997,
  Small: 23.1478,
};

/** Mean Strength Ladder score of the sampled species of each class — the point the
 *  within-class slope below is measured RELATIVE TO. */
export const CLASS_LADDER: Readonly<Record<string, number>> = {
  Female: 23.6604,
  Garden: 13.947,
  Headless: 17.5312,
  Large: 21.1308,
  Regular: 25.4347,
  Small: 17.7183,
};

/** One pooled within-class slope, effective points per Strength Ladder point.
 *
 *  Pooled rather than per class because three species per class cannot support six slopes.
 *  It is small — over the whole sampled ladder span it moves a species by about 7 points
 *  against a 6-point spread between class means — which is the finding restated: WHICH
 *  CLASS you field matters about as much as everything else put together. */
export const WITHIN_CLASS_SLOPE = 0.5842;

/** Provenance, so a number here can always be traced to the run that produced it. */
export const EFFECTIVE_FIT_META = {
  parties: 2500,
  heldOut: 500,
  fittedSpearman: 0.7783,
  ladderSpearman: 0.1517,
  sampledSpecies: 86,
} as const;
