// THE PROD GRID — every invasion flown by armies that real accounts actually fielded.
//
// The strength sweep asks "what does this fight do to an army of strength X", with X
// generated by a sampler. This asks the flatter and more awkward question: what does each
// fight do to the armies PEOPLE ACTUALLY BRING, at the level they bring them?
//
// Columns are PLAYER LEVEL, not a fitted strength band. A column holds real parties
// snapshotted out of `raid_sessions_v3.roster_json` — species, per-unit mutation mask and
// per-unit veterancy, IN THE ORDER THE PLAYER DEPLOYED THEM — taken from accounts that
// were within +/-2 levels of the column when they fought. Nothing here is composed, so
// nothing here can be wrong about what a player fields: the party floor, the deploy order,
// the duplicate stacking and the half-mutated bench units are all whatever they really are.
//
// NOBODY RETREATS. This is the point of the table. On the live service a late-game player
// reads a fight going wrong and bails, so the prod casualty rate measures how well people
// retreat rather than how dangerous a fight is — a non-win at level 45 costs zero zombies
// 86% of the time. The pilots never issue a `retreat` action, so every flight here runs to
// a conclusion and the loss column is the COUNTERFACTUAL: what the fight would have taken
// had the player played it out. That is the number an invasion should be tuned against.
//
// ROW ORDER is the level at which the row becomes content, descending (hardest first):
//   · a base invasion sits at its own `unlockLevel`
//   · an ELITE invasion sits at `clamp(unlockLevel + 10, 20, 44)` — Brain Tickets unlock
//     at 20, so no elite fight is content before then, and 44 is the ceiling because the
//     level cap is 45 and an elite row filed above every column would never be read.
import raidsJson from "../../../public/assets/raids/raids.json";
import prodArmiesJson from "../../../tmp/prod_armies.json";
import { buildFight } from "../buildFight";
import { buildPlayerUnits } from "../CombatEngine";
import { flyFight, type Flight } from "./pilot";
import { EXPERT, COMPETENT, makePilot, type PilotProfile } from "./pilots";
import { harnessFight } from "./raidFight";
import { makeOwned, type OwnedZombie } from "../../zombie/types";
import { ABILITY_TIER, abilityTierOf, MAX_VET_RANK } from "../../zombie/traits";
import zombiesJson from "../../../public/assets/zombies.json";
import type { RaidDef, ZombieDef } from "../types";

const raids = raidsJson as RaidDef[];
const CATALOG = zombiesJson as ZombieDef[];
const BY_KEY = new Map(CATALOG.map((z) => [z.key, z]));

/** One real party: [species key, mutation mask, survived invasions] per slot, in deploy
 *  order, exactly as the account sent it to /raid/start. */
type ProdUnit = [string, number, number];
interface ProdArmy { id: string; acct: string; units: ProdUnit[] }
const POOLS = prodArmiesJson as unknown as Record<string, ProdArmy[]>;

export const PROD_SHARDS = 6;
/** The columns. Each holds parties from accounts within +/-2 levels of it. */
export const COLUMNS: readonly number[] = [10, 15, 20, 25, 30, 35, 40, 45];
/** Wave seeds per army. One seed is one evening; the Robots' boss is drawn per seed. */
export const PROD_SEEDS = 3;
/** Which pilot the grid reports. Expert is the ceiling a human can plausibly reach, so a
 *  fight that costs casualties HERE costs them to anybody. */
export const PROD_PILOTS: readonly PilotProfile[] = [COMPETENT, EXPERT];

/** Where an elite invasion becomes content. Brain Tickets unlock at 20. */
export const eliteRowLevel = (unlock: number): number =>
  Math.min(44, Math.max(20, Math.floor(unlock) + 10));

export interface ProdRow {
  label: string;
  raidId: number;
  elite: boolean;
  tier: number;
  /** The level this row is filed at — see the header. */
  rowLevel: number;
  pilot: string;
  cells: ProdCell[];
}

export interface ProdCell {
  level: number;
  armies: number;
  flights: number;
  winRate: number;
  /** Win with ZERO casualties. The loss-less target. */
  losslessRate: number;
  /** Mean zombies lost per flight, nobody retreating. */
  meanLosses: number;
  /** Mean losses as a share of the party — a 20-army and a 13-army are not comparable
   *  on absolute casualties. */
  meanLossFrac: number;
  /** Ran the four-minute clock out with both sides standing. */
  timeoutRate: number;
  /** Timed out with a LIVING army that could not advance. A rules bug, not a number. */
  deadlockRate: number;
  /** Lost three quarters of the party or more — the cascade actually running. */
  wipeRate: number;
  medianWinSecs: number | null;
  /** Flights bucketed by casualties: `hist[n] = [won, lost]` is how many flights ended
   *  with exactly n zombies dead, split by whether the fight was won.
   *
   *  The mean alone cannot tell "everybody loses two" from "most lose none and one in ten
   *  loses eleven", and those are completely different fights to tune — the second is the
   *  cascade running, the first is a toll. Trimmed to the last non-empty bucket. */
  hist: [number, number][];
}

/** The rows, in the order the grid prints them: hardest (highest row level) first. */
export function prodRows(): { label: string; raidId: number; elite: boolean; tier: number; rowLevel: number }[] {
  const out: { label: string; raidId: number; elite: boolean; tier: number; rowLevel: number }[] = [];
  for (const raid of raids) {
    const unlock = Math.floor(raid.unlockLevel ?? 0);
    const dual = raid.id >= 12;
    // A dual invasion is scaled by its RUNG, not by a Brain Ticket (harnessFight ignores
    // `elite` on one), so it contributes its ladder ends instead of a base/elite pair.
    if (dual) {
      out.push({ label: `${raid.id} ${raid.name} t1`, raidId: raid.id, elite: false, tier: 1, rowLevel: unlock });
      out.push({ label: `${raid.id} ${raid.name} t10`, raidId: raid.id, elite: false, tier: 10, rowLevel: unlock });
      continue;
    }
    out.push({ label: `${raid.id} ${raid.name}`, raidId: raid.id, elite: false, tier: 0, rowLevel: unlock });
    out.push({ label: `${raid.id} ${raid.name} ★`, raidId: raid.id, elite: true, tier: 0, rowLevel: eliteRowLevel(unlock) });
  }
  return out.sort((a, b) => b.rowLevel - a.rowLevel || a.raidId - b.raidId || Number(a.elite) - Number(b.elite));
}

/** A real party, turned into combat units at the level the account actually held.
 *
 *  Rebuilt per flight because the sim MUTATES its units — a shared array would carry one
 *  fight's damage into the next. Ability tiers are left at 4: by level 20 the Lawyers are
 *  long beaten, and below that the party's own colour classes gate the kit anyway. */
function unitsFor(army: ProdArmy, playerLevel: number) {
  const party: OwnedZombie[] = army.units.map((u, i) => {
    const def = BY_KEY.get(u[0]);
    if (!def) throw new Error(`no species ${u[0]}`);
    return makeOwned(`z${i}`, def, 0, 0, Math.min(u[2], MAX_VET_RANK), u[1]);
  });
  return buildPlayerUnits(party, {
    abilityUnlocked: (key) => {
      const tier = abilityTierOf(key);
      return tier > 0 && tier <= 4 && ABILITY_TIER[tier].includes(key);
    },
    playerLevel,
  });
}

function cellFor(
  row: { raidId: number; elite: boolean; tier: number },
  level: number,
  profile: PilotProfile
): ProdCell {
  const pool = POOLS[String(level)] ?? [];
  const fs: (Flight & { size: number })[] = [];
  for (const army of pool) {
    for (let s = 0; s < PROD_SEEDS; s++) {
      const seed = `${row.raidId}:${row.tier}:${row.elite ? "e" : "b"}:${army.id}:${s}`;
      const { spec } = harnessFight({
        raidId: row.raidId,
        tier: row.tier || undefined,
        elite: row.elite,
        hazards: true,
        playerLevel: level,
        playerUnits: unitsFor(army, level),
        waveSeed: seed,
      });
      fs.push({ ...flyFight(buildFight(spec), makePilot(profile), { seed }), size: army.units.length });
    }
  }
  const n = fs.length || 1;
  const winSecs = fs.filter((f) => f.win).map((f) => f.secs).sort((a, b) => a - b);
  const hist: [number, number][] = [];
  for (const f of fs) {
    const bucket = Math.max(0, Math.round(f.losses));
    while (hist.length <= bucket) hist.push([0, 0]);
    hist[bucket][f.win ? 0 : 1]++;
  }
  return {
    level,
    armies: pool.length,
    flights: fs.length,
    winRate: fs.filter((f) => f.win).length / n,
    losslessRate: fs.filter((f) => f.win && f.losses === 0).length / n,
    meanLosses: fs.reduce((a, f) => a + f.losses, 0) / n,
    meanLossFrac: fs.reduce((a, f) => a + f.losses / Math.max(1, f.size), 0) / n,
    timeoutRate: fs.filter((f) => f.timedOut).length / n,
    deadlockRate: fs.filter((f) => f.deadlocked).length / n,
    wipeRate: fs.filter((f) => f.losses / Math.max(1, f.size) >= 0.75).length / n,
    medianWinSecs: winSecs.length ? winSecs[Math.floor(winSecs.length / 2)] : null,
    hist,
  };
}

/** One shard's slice of (row x pilot). Sharded on the flattened list so every worker gets
 *  a mix of cheap early raids and expensive late ones. */
export function runProdShard(shard: number, shards = PROD_SHARDS): ProdRow[] {
  const jobs = prodRows().flatMap((r) => PROD_PILOTS.map((p) => ({ r, p })));
  const out: ProdRow[] = [];
  for (let i = shard; i < jobs.length; i += shards) {
    const { r, p } = jobs[i];
    out.push({ ...r, pilot: p.id, cells: COLUMNS.map((L) => cellFor(r, L, p)) });
  }
  return out;
}
