// Server mirror of public/assets/placeables.json purchase economics. GENERATED —
// KEEP IN SYNC. Only the fields that decide VALUE are mirrored: buy cost + currency
// + source xp. The server prices a placeable BUY and REFUND from THIS table (never a
// client amount): buy debits `cost` (brains if `brains`, else gold) and grants XP
// using the recovered purchase formula;
// refund credits floor(cost * SELL_BACK_RATIO). Object ownership is tracked as a COUNT
// per key (like boosts) — placement/position stays client-side layout.
//
// The table below is GENERATED from that asset: `npm run catalogs` (server/
// scripts/gen-catalogs.mjs) rewrites the `#region generated:` block, and
// `npm run catalogs:check` fails CI and the deploy:prod gate when the two drift.
// Edit the ASSET, not the region. Everything outside the region is hand-written
// and is not touched.
//
// NOTE: the Zombie Pot has dynamic client pricing (500 first / 30 after) and stays a
// client-side purchase; it is still listed here for completeness but the client does
// not route its buy/refund through the server.
//
// EVERY category-"reward" placeable must be listed, including the 50 Epic Boss prizes.
// They are never bought, but object.refund resolves through this table, so a key that
// is absent cannot be SOLD at all (`bad_item`). They are priced at cost 0 like the
// other earned decorations — see objectRefund on why a free item must not refund the
// source's brain price.

import { awardedSellValue } from "../../src/awardSellValue";

export const SELL_BACK_RATIO = 0.2; // mirrors src/economy.ts ECONOMY.SELL_BACK_RATIO
export const BRAIN_SELL_GOLD_RATE = 1_000; // mirrors src/economy.ts

export interface ObjectEcon {
  cost: number;
  brains: boolean; // cost paid in brains, not gold
  xp: number;      // source XP for gold purchases; zero falls back to cost / 100
  /** Player level required to buy. -1 means NO requirement (59 seasonal/promo items),
   *  matching the client's `state.level < def.level` check, which -1 passes for free. */
  level: number;
  /** Simultaneous ownership cap for limited functional items. */
  purchaseLimit?: number;
}

export const OBJECTS: Readonly<Record<string, ObjectEcon>> = {
  // #region generated:OBJECTS
  // Source: public/assets/placeables.json — regenerate with `npm run catalogs` (server/scripts/gen-catalogs.mjs) — do not hand-edit
  "alienBanner": { cost: 0, brains: false, xp: 0, level: -1 },
  "antiHolidayIncinerator": { cost: 0, brains: false, xp: 0, level: -1 },
  "antiHolidayVault": { cost: 0, brains: false, xp: 0, level: -1 },
  "appleBobbing": { cost: 1500, brains: false, xp: 15, level: 1 },
  "aqueduct": { cost: 750, brains: false, xp: 7, level: 5 },
  "baloon": { cost: 900, brains: false, xp: 9, level: 21 },
  "baloon_black": { cost: 900, brains: false, xp: 9, level: 24 },
  "baloon_pink": { cost: 900, brains: false, xp: 9, level: 23 },
  "baloon_white": { cost: 900, brains: false, xp: 9, level: 22 },
  "bambooTree": { cost: 11300, brains: false, xp: 75, level: 26 },
  "banjo": { cost: 0, brains: false, xp: 0, level: -1 },
  "barbWireFence_01": { cost: 500, brains: false, xp: 5, level: 8 },
  "barrelNormal": { cost: 400, brains: false, xp: 4, level: 4 },
  "barrelNormal_blue": { cost: 750, brains: false, xp: 7, level: 6 },
  "barrelNormal_pink": { cost: 750, brains: false, xp: 7, level: 5 },
  "barrelNormal_red": { cost: 750, brains: false, xp: 7, level: 9 },
  "barrelOfFireworks": { cost: 10000, brains: false, xp: 100, level: 1 },
  "bbqGrill": { cost: 1, brains: true, xp: 0, level: 1 },
  "beachBall": { cost: 1, brains: true, xp: 0, level: 1 },
  "bedazzledGravestone": { cost: 0, brains: false, xp: 0, level: -1 },
  "beechTree": { cost: 4500, brains: false, xp: 33, level: 15 },
  "bigDragonBoat": { cost: 2, brains: true, xp: 0, level: 1 },
  "bigEasterEggBlue": { cost: 1, brains: true, xp: 0, level: 1 },
  "bigEasterEggGreen": { cost: 1, brains: true, xp: 0, level: 1 },
  "bigEasterEggPink": { cost: 1, brains: true, xp: 0, level: 1 },
  "bike": { cost: 2, brains: true, xp: 1000, level: 36 },
  "birdhouse": { cost: 10000, brains: false, xp: 100, level: 41 },
  "birthdayBalloonsRight": { cost: 500, brains: false, xp: 5, level: 1 },
  "birthdayCakeThirdYearRight": { cost: 10, brains: false, xp: 0, level: 1 },
  "birthdayTimStatue": { cost: 8, brains: true, xp: 0, level: 1 },
  "blueBox": { cost: 2000, brains: false, xp: 20, level: 25 },
  "blueSatchet": { cost: 1, brains: true, xp: 0, level: 1 },
  "bonfire": { cost: 2000, brains: false, xp: 20, level: 13 },
  "boots": { cost: 0, brains: false, xp: 0, level: -1 },
  "boulder": { cost: 1500, brains: false, xp: 15, level: 22 },
  "boxoLantern": { cost: 5, brains: true, xp: 0, level: -1 },
  "brokenTractor": { cost: 0, brains: false, xp: 0, level: -1 },
  "brokenWagon": { cost: 15000, brains: false, xp: 150, level: 41 },
  "bullseye": { cost: 5000, brains: false, xp: 50, level: 42 },
  "bunchOfCandles": { cost: 3000, brains: false, xp: 30, level: 8 },
  "butterChurn": { cost: 5000, brains: false, xp: 50, level: 37 },
  "cactusTarget": { cost: 0, brains: false, xp: 0, level: -1 },
  "cameraNormal": { cost: 1, brains: true, xp: 100, level: 1, purchaseLimit: 1 },
  "candelabra": { cost: 1000, brains: false, xp: 10, level: -1 },
  "candle": { cost: 1000, brains: false, xp: 10, level: 4 },
  "candleAltarDay": { cost: 2, brains: true, xp: 0, level: -1 },
  "cannon": { cost: 2, brains: true, xp: 0, level: 1 },
  "cannonBalls": { cost: 5000, brains: false, xp: 50, level: 1 },
  "carecrowNormal": { cost: 20000, brains: false, xp: 200, level: 19 },
  "carnivorousPlants": { cost: 0, brains: false, xp: 0, level: -1 },
  "cemeteryFence_01": { cost: 900, brains: false, xp: 9, level: 23 },
  "cemeteryFence_01_pink": { cost: 900, brains: false, xp: 9, level: 24 },
  "chariot": { cost: 1500, brains: false, xp: 15, level: 5 },
  "chocolateBunnyA": { cost: 2, brains: true, xp: 0, level: 1 },
  "chocolateBunnyB": { cost: 2, brains: true, xp: 0, level: 1 },
  "chocolateTile": { cost: 3000, brains: false, xp: 30, level: 26 },
  "circusFlagBlue": { cost: 0, brains: false, xp: 0, level: -1 },
  "circusFlagGreen": { cost: 0, brains: false, xp: 0, level: -1 },
  "circusFlagYellow": { cost: 0, brains: false, xp: 0, level: -1 },
  "circusPopcorn": { cost: 0, brains: false, xp: 0, level: -1 },
  "circusTent": { cost: 0, brains: false, xp: 0, level: -1 },
  "cityLamp": { cost: 1800, brains: false, xp: 18, level: 24 },
  "cobblestoneRoadBend_01": { cost: 1500, brains: false, xp: 15, level: 20 },
  "cobblestoneRoadIntersection": { cost: 1500, brains: false, xp: 15, level: 20 },
  "cobblestoneRoadStraight_01": { cost: 1500, brains: false, xp: 15, level: 20 },
  "coconutTree": { cost: 2300, brains: false, xp: 23, level: 9 },
  "coffin1": { cost: 0, brains: false, xp: 0, level: -1 },
  "coffin2": { cost: 0, brains: false, xp: 0, level: -1 },
  "coffin3": { cost: 0, brains: false, xp: 0, level: -1 },
  "colossus": { cost: 3, brains: true, xp: 0, level: 5 },
  "column": { cost: 1, brains: true, xp: 0, level: 5 },
  "coolerLarge": { cost: 6000, brains: false, xp: 60, level: 14 },
  "coolerSmall": { cost: 5000, brains: false, xp: 50, level: 11 },
  "cornucopia": { cost: 2000, brains: false, xp: 20, level: 1 },
  "corporatevilleBanner": { cost: 0, brains: false, xp: 0, level: -1 },
  "cottonCandyTree": { cost: 1500, brains: false, xp: 15, level: 7 },
  "crashedUFO": { cost: 0, brains: false, xp: 0, level: -1 },
  "crate": { cost: 500, brains: false, xp: 5, level: 22 },
  "crate_black": { cost: 750, brains: false, xp: 5, level: 25 },
  "crate_blue": { cost: 750, brains: false, xp: 5, level: 23 },
  "crate_pink": { cost: 750, brains: false, xp: 5, level: 27 },
  "crate_red": { cost: 750, brains: false, xp: 5, level: 24 },
  "crate_white": { cost: 750, brains: false, xp: 5, level: 26 },
  "crate_yellow": { cost: 750, brains: false, xp: 5, level: 28 },
  "croquet": { cost: 10000, brains: false, xp: 100, level: 42 },
  "crystalGazebo": { cost: 0, brains: false, xp: 0, level: -1 },
  "cupidStatueA": { cost: 50, brains: true, xp: 3000, level: 1 },
  "cupidStatueB": { cost: 50, brains: true, xp: 3000, level: 1 },
  "cupidTopiary": { cost: 5000, brains: false, xp: 100, level: 1 },
  "cursedChest": { cost: 2, brains: true, xp: 0, level: 1 },
  "cypressTree": { cost: 500, brains: false, xp: 5, level: 3 },
  "daisy": { cost: 10, brains: false, xp: 0, level: 6 },
  "desertSkull": { cost: 3000, brains: false, xp: 30, level: 26 },
  "diamondCar": { cost: 0, brains: false, xp: 0, level: -1 },
  "dinosaurFern": { cost: 5000, brains: false, xp: 50, level: 28 },
  "dinosaurFootprint": { cost: 2500, brains: false, xp: 25, level: 25 },
  "dinosaurJeep": { cost: 5, brains: true, xp: 0, level: 27 },
  "dinosaurRaptor": { cost: 3, brains: true, xp: 0, level: 25 },
  "dinosaurSkull": { cost: 1, brains: true, xp: 0, level: 19 },
  "dinosaurTriceratops": { cost: 8, brains: true, xp: 0, level: 29 },
  "doubleRainbow_01": { cost: 2, brains: true, xp: 1000, level: 26 },
  "dragonStatue": { cost: 4, brains: true, xp: 0, level: 1 },
  "drgroundhogBurrow": { cost: 0, brains: false, xp: 0, level: -1 },
  "drgroundhogDistillery": { cost: 0, brains: false, xp: 0, level: -1 },
  "drgroundhogEvilDevice": { cost: 0, brains: false, xp: 0, level: -1 },
  "drgroundhogEvilLab": { cost: 0, brains: false, xp: 0, level: -1 },
  "drgroundhogLabShelves": { cost: 0, brains: false, xp: 0, level: -1 },
  "drgroundhogLabTable": { cost: 0, brains: false, xp: 0, level: -1 },
  "drgroundhogNutStash": { cost: 0, brains: false, xp: 0, level: -1 },
  "drgroundhogTricycle": { cost: 0, brains: false, xp: 0, level: -1 },
  "drinksCooler": { cost: 1, brains: true, xp: 0, level: 1 },
  "easterBasket": { cost: 2, brains: true, xp: 0, level: 1 },
  "easterEggBlue": { cost: 500, brains: false, xp: 5, level: 1 },
  "easterEggGreen": { cost: 500, brains: false, xp: 5, level: 1 },
  "easterEggPink": { cost: 500, brains: false, xp: 5, level: 1 },
  "easterEggPurple": { cost: 500, brains: false, xp: 5, level: 1 },
  "easterEggWhite": { cost: 400, brains: false, xp: 4, level: 1 },
  "easterGrass": { cost: 1500, brains: false, xp: 15, level: 1 },
  "eggBush": { cost: 1, brains: true, xp: 0, level: 1 },
  "eggLamp": { cost: 3, brains: true, xp: 0, level: 1 },
  "eggTree": { cost: 3, brains: true, xp: 0, level: 1 },
  "enormoPumpkin": { cost: 2, brains: true, xp: 0, level: 1 },
  "evergreenTree": { cost: 11300, brains: false, xp: 113, level: 32 },
  "evilCarriage": { cost: 0, brains: false, xp: 0, level: -1 },
  "evilMirror": { cost: 0, brains: false, xp: 0, level: -1 },
  "fancyChair": { cost: 10000, brains: false, xp: 100, level: 31 },
  "fancyCoatOfArms": { cost: 2, brains: true, xp: 0, level: 22 },
  "fancyFireplace": { cost: 3, brains: true, xp: 0, level: 1 },
  "fancyFountain": { cost: 0, brains: false, xp: 0, level: -1 },
  "fancyMustache": { cost: 10000, brains: false, xp: 100, level: 30 },
  "fancyTeacup": { cost: 2, brains: true, xp: 0, level: 22 },
  "fancyTeakettle": { cost: 5, brains: true, xp: 0, level: 28 },
  "fancyUmbrellaTree": { cost: 3, brains: true, xp: 0, level: 26 },
  "fashionableScarecrow": { cost: 0, brains: false, xp: 0, level: -1 },
  "fenceGate_01_closed": { cost: 500, brains: false, xp: 5, level: 2 },
  "fenceGate_01_closed_black": { cost: 1000, brains: false, xp: 10, level: 12 },
  "fenceGate_01_closed_blue": { cost: 1000, brains: false, xp: 10, level: 4 },
  "fenceGate_01_closed_pink": { cost: 1000, brains: false, xp: 10, level: 3 },
  "fenceGate_01_closed_red": { cost: 1000, brains: false, xp: 10, level: 10 },
  "fenceGate_01_open": { cost: 500, brains: false, xp: 5, level: 2 },
  "fenceGate_01_open_black": { cost: 1000, brains: false, xp: 10, level: 12 },
  "fenceGate_01_open_blue": { cost: 1000, brains: false, xp: 10, level: 4 },
  "fenceGate_01_open_pink": { cost: 1000, brains: false, xp: 10, level: 3 },
  "fenceGate_01_open_red": { cost: 1000, brains: false, xp: 10, level: 10 },
  "festiveFence": { cost: 1000, brains: false, xp: 10, level: -1 },
  "fireRing": { cost: 0, brains: false, xp: 0, level: -1 },
  "fireflies": { cost: 0, brains: false, xp: 0, level: -1 },
  "flowerBed": { cost: 200, brains: false, xp: 2, level: 9 },
  "flowerBedViolet": { cost: 200, brains: false, xp: 2, level: 9 },
  "flowerBedYellow": { cost: 200, brains: false, xp: 2, level: 9 },
  "flowerBed_white": { cost: 200, brains: false, xp: 2, level: 9 },
  "fountain": { cost: 1, brains: true, xp: 500, level: 16 },
  "fruitTreeApple": { cost: 500, brains: false, xp: 5, level: 1 },
  "fruitTreeLemon": { cost: 2000, brains: false, xp: 20, level: 10 },
  "fruitTreeOrange": { cost: 1000, brains: false, xp: 10, level: 15 },
  "gallows": { cost: 2, brains: true, xp: 1000, level: 21 },
  "gazeboNormal": { cost: 100000, brains: false, xp: 1000, level: 20 },
  "generalLarvaelusBanner": { cost: 0, brains: false, xp: 0, level: -1 },
  "generalLarvaelusTeleporterA": { cost: 0, brains: false, xp: 0, level: -1 },
  "generalLarvaelusTeleporterB": { cost: 0, brains: false, xp: 0, level: -1 },
  "geyser": { cost: 3, brains: true, xp: 0, level: 34 },
  "giantCandyCane": { cost: 1, brains: true, xp: 500, level: 26 },
  "giantClamClosed": { cost: 0, brains: false, xp: 0, level: -1 },
  "giantPeep": { cost: 2, brains: true, xp: 0, level: 1 },
  "gibbetCage": { cost: 3, brains: true, xp: 0, level: 1 },
  "giftBasket": { cost: 3000, brains: false, xp: 30, level: 1 },
  "glowFlowerDay": { cost: 500, brains: false, xp: 5, level: 20 },
  "glowMushroomDay": { cost: 400, brains: false, xp: 4, level: 10 },
  "glowSkullDay": { cost: 500, brains: false, xp: 5, level: 30 },
  "glowStoneDay": { cost: 250, brains: false, xp: 2, level: 1 },
  "gnomeStatue": { cost: 2, brains: true, xp: 200, level: 44 },
  "goldEgg": { cost: 5, brains: true, xp: 0, level: 1 },
  "grainSilo": { cost: 4500, brains: false, xp: 45, level: 33 },
  "graveAngel": { cost: 1000, brains: false, xp: 10, level: 20 },
  "graveFlat": { cost: 500, brains: false, xp: 5, level: 1 },
  "graveGargoyle": { cost: 1000, brains: false, xp: 10, level: 30 },
  "graveOld": { cost: 800, brains: false, xp: 8, level: 10 },
  "gravestoneBlue": { cost: 2, brains: true, xp: 400, level: 1, purchaseLimit: 1 },
  "gravestoneNormal": { cost: 800, brains: false, xp: 8, level: 5 },
  "gravestoneNormal_black": { cost: 1750, brains: false, xp: 17, level: 13 },
  "gravestoneNormal_pink": { cost: 1500, brains: false, xp: 15, level: 7 },
  "gravestoneObsidian": { cost: 8, brains: true, xp: 400, level: 40, purchaseLimit: 1 },
  "gravestoneRed": { cost: 4, brains: true, xp: 400, level: 15, purchaseLimit: 1 },
  "gravestoneRound": { cost: 800, brains: false, xp: 8, level: 5 },
  "gravestoneSilver": { cost: 6, brains: true, xp: 400, level: 25, purchaseLimit: 1 },
  "greenGift": { cost: 0, brains: false, xp: 0, level: -1 },
  "gunRack": { cost: 0, brains: false, xp: 0, level: -1 },
  "hauntedClocktower": { cost: 0, brains: false, xp: 0, level: -1 },
  "hauntedHouse": { cost: 3, brains: true, xp: 0, level: -1 },
  "haystack": { cost: 2500, brains: false, xp: 25, level: 11 },
  "hazardFence": { cost: 0, brains: false, xp: 0, level: -1 },
  "heartCandle": { cost: 5000, brains: false, xp: 100, level: 1 },
  "heartFountain": { cost: 10, brains: true, xp: 6000, level: 1 },
  "heartGravestone": { cost: 15, brains: true, xp: 1750, level: 1 },
  "heartHedge": { cost: 5000, brains: false, xp: 100, level: 1 },
  "hedge_01": { cost: 1000, brains: false, xp: 10, level: 7 },
  "hedge_01_black": { cost: 2000, brains: false, xp: 18, level: 18 },
  "hedge_01_blue": { cost: 1800, brains: false, xp: 18, level: 10 },
  "hedge_01_pink": { cost: 2000, brains: false, xp: 10, level: 20 },
  "hedge_01_red": { cost: 1800, brains: false, xp: 18, level: 8 },
  "hedge_01_white": { cost: 1800, brains: false, xp: 18, level: 14 },
  "hideout": { cost: 0, brains: false, xp: 0, level: -1 },
  "holidayBalloonRed": { cost: 5000, brains: false, xp: 50, level: 1 },
  "holidayBalloonWhite": { cost: 1, brains: true, xp: 0, level: 1 },
  "holidayBalloonYellow": { cost: 1, brains: true, xp: 0, level: 1 },
  "holidayChocolateFountain": { cost: 10, brains: true, xp: 0, level: 1 },
  "holidayHeartTopiary": { cost: 5000, brains: false, xp: 50, level: 1 },
  "holidayRoseBushRed": { cost: 15000, brains: false, xp: 150, level: 1 },
  "holidayRoseBushWhite": { cost: 3, brains: true, xp: 0, level: 1 },
  "holidayRoseBushYellow": { cost: 3, brains: true, xp: 0, level: 1 },
  "hotdogCart": { cost: 10000, brains: false, xp: 100, level: 45 },
  "iceCreamConeChocolate": { cost: 0, brains: false, xp: 0, level: -1 },
  "iceCreamConeStrawberry": { cost: 0, brains: false, xp: 0, level: -1 },
  "iceCreamConeVanilla": { cost: 0, brains: false, xp: 0, level: -1 },
  "iceCreamStand": { cost: 0, brains: false, xp: 0, level: -1 },
  "iceCreamTruck": { cost: 0, brains: false, xp: 0, level: -1 },
  "iceSculpture": { cost: 3, brains: true, xp: 0, level: 1 },
  "igloo": { cost: 3, brains: true, xp: 0, level: 1 },
  "ironGate_01_closed": { cost: 1800, brains: false, xp: 18, level: 23 },
  "ironGate_01_closed_pink": { cost: 1800, brains: false, xp: 18, level: 24 },
  "ironGate_01_open": { cost: 1800, brains: false, xp: 18, level: 23 },
  "ironGate_01_open_pink": { cost: 1800, brains: false, xp: 18, level: 24 },
  "islandRelic": { cost: 20000, brains: false, xp: 200, level: 1 },
  "jewelHome": { cost: 0, brains: false, xp: 0, level: -1 },
  "koiPond": { cost: 5, brains: true, xp: 500, level: 44 },
  "lawnmower": { cost: 7000, brains: false, xp: 70, level: 45 },
  "leafPile": { cost: 10, brains: false, xp: 0, level: 11 },
  "lemonadeStand": { cost: 9000, brains: false, xp: 90, level: 38 },
  "libertyBell": { cost: 5, brains: true, xp: 0, level: 1 },
  "libertyMonument": { cost: 100000, brains: false, xp: 1000, level: 1 },
  "libertySnareDrum": { cost: 2, brains: true, xp: 0, level: 1 },
  "lifeguardChair": { cost: 3, brains: true, xp: 0, level: 1 },
  "lilyJukebox": { cost: 0, brains: false, xp: 0, level: -1 },
  "logCabin": { cost: 4, brains: true, xp: 2000, level: 36 },
  "lollipop": { cost: 1500, brains: false, xp: 15, level: 21 },
  "lotusLantern": { cost: 2, brains: true, xp: 0, level: 1 },
  "loveShack": { cost: 0, brains: false, xp: 0, level: -1 },
  "luckPlant": { cost: 1000, brains: false, xp: 10, level: 1 },
  "mailboxNormal": { cost: 950, brains: false, xp: 9, level: 8 },
  "mausoleum10": { cost: 4, brains: true, xp: 300, level: 1, purchaseLimit: 1 },
  "mausoleum11": { cost: 4, brains: true, xp: 300, level: 1, purchaseLimit: 1 },
  "mausoleum12": { cost: 4, brains: true, xp: 300, level: 1, purchaseLimit: 1 },
  "mausoleum3": { cost: 8, brains: true, xp: 300, level: 1, purchaseLimit: 1 },
  "mausoleum4": { cost: 4, brains: true, xp: 300, level: 1, purchaseLimit: 1 },
  "mausoleum5": { cost: 4, brains: true, xp: 300, level: 1, purchaseLimit: 1 },
  "mausoleum6": { cost: 4, brains: true, xp: 300, level: 1, purchaseLimit: 1 },
  "mausoleum7": { cost: 4, brains: true, xp: 300, level: 1, purchaseLimit: 1 },
  "mausoleum8": { cost: 4, brains: true, xp: 300, level: 1, purchaseLimit: 1 },
  "mausoleum9": { cost: 4, brains: true, xp: 300, level: 1, purchaseLimit: 1 },
  "mayflower": { cost: 5, brains: true, xp: 0, level: 1 },
  "mechanicalBull": { cost: 0, brains: false, xp: 0, level: -1 },
  "memorialStatue": { cost: 3000, brains: false, xp: 30, level: 1 },
  "monkeyBars": { cost: 4000, brains: false, xp: 40, level: 40 },
  "monolithBusted": { cost: 3, brains: true, xp: 800, level: 25 },
  "monolithCombine": { cost: 12, brains: true, xp: 6000, level: 25, purchaseLimit: 1 },
  "monolithEgg": { cost: 2, brains: true, xp: 0, level: 1 },
  "monolithMutation": { cost: 8, brains: true, xp: 800, level: 1, purchaseLimit: 1 },
  "monolithPlowing": { cost: 10, brains: true, xp: 1000, level: 1, purchaseLimit: 1 },
  "monolithSpeed": { cost: 10, brains: true, xp: 1000, level: 1, purchaseLimit: 1 },
  "monolithZombie": { cost: 10, brains: true, xp: 1000, level: 1, purchaseLimit: 1 },
  "monument": { cost: 0, brains: false, xp: 0, level: -1 },
  "mossyCouch": { cost: 0, brains: false, xp: 0, level: -1 },
  "muddyPool": { cost: 0, brains: false, xp: 0, level: -1 },
  "mysticalMambaBanner": { cost: 0, brains: false, xp: 0, level: -1 },
  "mysticalMambasWishMachineLeft": { cost: 0, brains: false, xp: 0, level: -1 },
  "newYearBallLeft": { cost: 3000, brains: false, xp: 30, level: 1 },
  "newYearBallRight": { cost: 3000, brains: false, xp: 30, level: 1 },
  "newYearBannerLeft": { cost: 1500, brains: false, xp: 15, level: 1 },
  "newYearBannerRight": { cost: 1500, brains: false, xp: 15, level: 1 },
  "newYearTree": { cost: 2500, brains: false, xp: 25, level: 1 },
  "ninjaBanner": { cost: 0, brains: false, xp: 0, level: -1 },
  "oakTree": { cost: 900, brains: false, xp: 9, level: 5 },
  "oldMcDonnellBanner": { cost: 0, brains: false, xp: 0, level: -1 },
  "oliveTreeOlive": { cost: 1000, brains: false, xp: 10, level: 5 },
  "olympus": { cost: 5, brains: true, xp: 500, level: 44 },
  "organ": { cost: 2, brains: true, xp: 0, level: -1 },
  "outhouseNormal": { cost: 2250, brains: false, xp: 22, level: 13 },
  "outhouseNormal_blue": { cost: 4500, brains: false, xp: 45, level: 17 },
  "outhouseNormal_pink": { cost: 4500, brains: false, xp: 45, level: 15 },
  "outhouseNormal_red": { cost: 4500, brains: false, xp: 45, level: 19 },
  "pagoda": { cost: 7, brains: true, xp: 0, level: 1 },
  "pailAndShovel": { cost: 4000, brains: false, xp: 40, level: 1 },
  "palmTree": { cost: 15900, brains: false, xp: 93, level: 29 },
  "parrot": { cost: 0, brains: false, xp: 0, level: -1 },
  "patioBench": { cost: 800, brains: false, xp: 8, level: 1 },
  "patioTable": { cost: 4, brains: true, xp: 0, level: 1 },
  "peepPink": { cost: 800, brains: false, xp: 8, level: 1 },
  "peepYellow": { cost: 800, brains: false, xp: 8, level: 1 },
  "pen_01": { cost: 250, brains: false, xp: 2, level: 2 },
  "pen_01_black": { cost: 500, brains: false, xp: 5, level: 12 },
  "pen_01_blue": { cost: 500, brains: false, xp: 5, level: 4 },
  "pen_01_pink": { cost: 500, brains: false, xp: 5, level: 3 },
  "pen_01_red": { cost: 500, brains: false, xp: 5, level: 10 },
  "perfumeVat": { cost: 0, brains: false, xp: 0, level: -1 },
  "pettingZoo": { cost: 200, brains: false, xp: 2, level: -1, purchaseLimit: 1 },
  "picnicNormal": { cost: 4000, brains: false, xp: 40, level: 17 },
  "pirateBag": { cost: 2000, brains: false, xp: 20, level: 1 },
  "pirateBanner": { cost: 0, brains: false, xp: 0, level: -1 },
  "pirateBarrel": { cost: 10000, brains: false, xp: 100, level: 1 },
  "pirateCrate": { cost: 1, brains: true, xp: 0, level: 1 },
  "pirateCratePlain": { cost: 2000, brains: false, xp: 20, level: 1 },
  "pirateSack": { cost: 2000, brains: false, xp: 20, level: 1 },
  "pixelBanner": { cost: 0, brains: false, xp: 0, level: -1 },
  "pixelBrick": { cost: 0, brains: false, xp: 0, level: -1 },
  "pixelBrickFloating": { cost: 0, brains: false, xp: 0, level: -1 },
  "pixelCampfire": { cost: 0, brains: false, xp: 0, level: -1 },
  "pixelTower": { cost: 0, brains: false, xp: 0, level: -1 },
  "pixelTree": { cost: 0, brains: false, xp: 0, level: -1 },
  "pond": { cost: 75000, brains: false, xp: 750, level: 16 },
  "pond1": { cost: 800, brains: false, xp: 8, level: 17 },
  "pond2": { cost: 800, brains: false, xp: 8, level: 19 },
  "pond3": { cost: 800, brains: false, xp: 8, level: 16 },
  "pond4": { cost: 800, brains: false, xp: 8, level: 17 },
  "pond5": { cost: 800, brains: false, xp: 8, level: 14 },
  "pond6": { cost: 800, brains: false, xp: 8, level: 18 },
  "pond7": { cost: 800, brains: false, xp: 8, level: 13 },
  "postalMailBox": { cost: 3000, brains: false, xp: 30, level: 40 },
  "powderKeg": { cost: 1, brains: true, xp: 0, level: 1 },
  "pumpkin": { cost: 1000, brains: false, xp: 10, level: 1 },
  "pumpkinAngry": { cost: 9000, brains: false, xp: 90, level: 31 },
  "pumpkinHappy": { cost: 9000, brains: false, xp: 90, level: 29 },
  "pumpkinMan": { cost: 3, brains: true, xp: 1500, level: 31 },
  "pyramid": { cost: 200000, brains: false, xp: 2000, level: 35 },
  "redGift": { cost: 0, brains: false, xp: 0, level: -1 },
  "redLantern": { cost: 2, brains: true, xp: 0, level: 1 },
  "redSatchet": { cost: 1, brains: true, xp: 0, level: 1 },
  "redTractor": { cost: 50, brains: true, xp: 0, level: 34 },
  "riceDumpling": { cost: 10000, brains: false, xp: 100, level: 1 },
  "riceDumplingPile": { cost: 3, brains: true, xp: 0, level: 1 },
  "roadBend_01": { cost: 800, brains: false, xp: 8, level: 8 },
  "roadIntersection": { cost: 850, brains: false, xp: 8, level: 8 },
  "roadStraight": { cost: 750, brains: false, xp: 7, level: 8 },
  "robotBanner": { cost: 0, brains: false, xp: 0, level: -1 },
  "rockBunny": { cost: 0, brains: false, xp: 0, level: -1 },
  "rockLobster": { cost: 0, brains: false, xp: 0, level: -1 },
  "rockingHorse": { cost: 0, brains: false, xp: 0, level: -1 },
  "rocks": { cost: 50, brains: false, xp: 0, level: 12 },
  "rockyRhinosBanner": { cost: 0, brains: false, xp: 0, level: -1 },
  "rockyRhinosCave": { cost: 0, brains: false, xp: 0, level: -1 },
  "rockyRhinosGong": { cost: 0, brains: false, xp: 0, level: -1 },
  "rockyRhinosSculpture": { cost: 0, brains: false, xp: 0, level: -1 },
  "rope": { cost: 2000, brains: false, xp: 20, level: 1 },
  "rubberTree": { cost: 7500, brains: false, xp: 45, level: 20 },
  "rumBarrel": { cost: 2000, brains: false, xp: 20, level: 1 },
  "saddle": { cost: 0, brains: false, xp: 0, level: -1 },
  "sakuraTree": { cost: 3000, brains: false, xp: 30, level: 12 },
  "sakuraTreeFlowering": { cost: 6000, brains: false, xp: 60, level: 24 },
  "sakuraTreeWeeping": { cost: 4500, brains: false, xp: 45, level: 18 },
  "saloon": { cost: 0, brains: false, xp: 0, level: -1 },
  "sandCastle": { cost: 5, brains: true, xp: 0, level: 1 },
  "sandDollar": { cost: 0, brains: false, xp: 0, level: -1 },
  "scarecrowNormal": { cost: 12000, brains: false, xp: 120, level: 18 },
  "sculptureOfLiberty": { cost: 5, brains: true, xp: 0, level: 1 },
  "setiDish": { cost: 0, brains: false, xp: 0, level: -1 },
  "shamrocks": { cost: 10, brains: false, xp: 0, level: 7 },
  "shellScallop": { cost: 50, brains: false, xp: 0, level: 3 },
  "shellTrumpet": { cost: 75, brains: false, xp: 0, level: 6 },
  "shipWheel": { cost: 2, brains: true, xp: 0, level: 1 },
  "skeletonCouple": { cost: 3, brains: true, xp: 0, level: -1 },
  "skullCandle": { cost: 4500, brains: false, xp: 45, level: 28 },
  "skullWithSnake": { cost: 4000, brains: false, xp: 40, level: 27 },
  "sleigh": { cost: 2, brains: true, xp: 1000, level: 1 },
  "smallCactus": { cost: 3300, brains: false, xp: 7, level: 12 },
  "smallDragonBoat": { cost: 2, brains: true, xp: 0, level: 1 },
  "snowBalls": { cost: 1500, brains: false, xp: 15, level: 1 },
  "snowCannon": { cost: 5, brains: true, xp: 0, level: 1 },
  "snowFarmhand": { cost: 0, brains: false, xp: 0, level: -1 },
  "snowFort": { cost: 7500, brains: false, xp: 75, level: 1 },
  "snowHedge_01": { cost: 5000, brains: false, xp: 50, level: 30 },
  "snowLumberjack": { cost: 0, brains: false, xp: 0, level: -1 },
  "snowMan": { cost: 3, brains: true, xp: 1500, level: 1 },
  "snowOlMcDonnell": { cost: 0, brains: false, xp: 0, level: -1 },
  "snowOwl": { cost: 0, brains: false, xp: 0, level: -1 },
  "snowZombie": { cost: 0, brains: false, xp: 0, level: -1 },
  "soilDivider": { cost: 1, brains: true, xp: 50, level: 19 },
  "soil_zombiePatch": { cost: 3, brains: true, xp: 300, level: 1, purchaseLimit: 1 },
  "spaceCrater": { cost: 1000, brains: false, xp: 10, level: 21 },
  "spaceLunarLander": { cost: 2, brains: true, xp: 0, level: 22 },
  "spaceMoon": { cost: 10000, brains: false, xp: 100, level: 31 },
  "spaceRocketShip": { cost: 3, brains: true, xp: 0, level: 25 },
  "spaceSolarSystem": { cost: 5, brains: true, xp: 0, level: 1 },
  "spaceWormHoleA": { cost: 3, brains: true, xp: 0, level: 1 },
  "spaceWormHoleB": { cost: 3, brains: true, xp: 0, level: 1 },
  "spookyStrawmanRight": { cost: 2, brains: true, xp: 0, level: -1 },
  "squirmyWorms": { cost: 0, brains: false, xp: 0, level: -1 },
  "stPatricksClover": { cost: 2, brains: true, xp: 0, level: 1 },
  "stPatricksFountain": { cost: 5, brains: true, xp: 0, level: 1 },
  "stPatricksIrishFlag": { cost: 10000, brains: false, xp: 100, level: 1 },
  "stPatricksPotOfGold": { cost: 2, brains: true, xp: 0, level: 1 },
  "stPatricksShamrock": { cost: 10000, brains: false, xp: 100, level: 1 },
  "starTopiary": { cost: 3000, brains: false, xp: 30, level: 1 },
  "starfish": { cost: 50, brains: false, xp: 0, level: 9 },
  "stoneDivider": { cost: 1, brains: true, xp: 50, level: 19 },
  "stoneLion": { cost: 3, brains: true, xp: 0, level: 1 },
  "storage01": { cost: 0, brains: false, xp: 0, level: 1, purchaseLimit: 1 },
  "storage02": { cost: 15000, brains: false, xp: 150, level: 1, purchaseLimit: 1 },
  "storage03": { cost: 30000, brains: false, xp: 300, level: 1, purchaseLimit: 1 },
  "storage04": { cost: 60000, brains: false, xp: 600, level: 1, purchaseLimit: 1 },
  "storage05": { cost: 95000, brains: false, xp: 950, level: 1, purchaseLimit: 1 },
  "storage06": { cost: 145000, brains: false, xp: 1450, level: 1, purchaseLimit: 1 },
  "storage07": { cost: 225000, brains: false, xp: 2250, level: 1, purchaseLimit: 1 },
  "storage08": { cost: 350000, brains: false, xp: 3500, level: 1, purchaseLimit: 1 },
  "storage09": { cost: 525000, brains: false, xp: 5250, level: 1, purchaseLimit: 1 },
  "streetLight": { cost: 3000, brains: false, xp: 30, level: 28 },
  "sugarSkull": { cost: 4000, brains: false, xp: 40, level: -1 },
  "sundial": { cost: 2, brains: true, xp: 0, level: 37 },
  "surfboardBlue": { cost: 1, brains: true, xp: 0, level: 1 },
  "surfboardRed": { cost: 2, brains: true, xp: 0, level: 1 },
  "swamp_Cabin": { cost: 0, brains: false, xp: 0, level: -1 },
  "swingSet": { cost: 10000, brains: false, xp: 100, level: 39 },
  "taikoDrum": { cost: 0, brains: false, xp: 0, level: -1 },
  "tallCactus": { cost: 1, brains: true, xp: 500, level: 18 },
  "teddyBear": { cost: 0, brains: false, xp: 0, level: -1 },
  "teddyValentine": { cost: 0, brains: false, xp: 0, level: -1 },
  "telephonePole": { cost: 2200, brains: false, xp: 22, level: 27 },
  "teleporter": { cost: 0, brains: false, xp: 0, level: -1 },
  "temple": { cost: 2, brains: true, xp: 0, level: 5 },
  "tentNormal": { cost: 1, brains: true, xp: 500, level: 1 },
  "tentNormal_blue": { cost: 5000, brains: false, xp: 50, level: 16 },
  "tentNormal_pink": { cost: 5000, brains: false, xp: 50, level: 14 },
  "tentNormal_plain": { cost: 3000, brains: false, xp: 30, level: 10 },
  "tikiHeadLarge": { cost: 2, brains: true, xp: 0, level: 1 },
  "tikiHeadSmall": { cost: 2, brains: true, xp: 0, level: 1 },
  "tikiTorch": { cost: 1, brains: true, xp: 0, level: 29 },
  "toadStool": { cost: 0, brains: false, xp: 0, level: -1 },
  "totemPole": { cost: 1, brains: true, xp: 500, level: 8 },
  "toxicDrum": { cost: 0, brains: false, xp: 0, level: -1 },
  "treasureChest": { cost: 1, brains: true, xp: 500, level: 21 },
  "treeAmiable": { cost: 800, brains: false, xp: 8, level: 20 },
  "treeAutumn1": { cost: 2000, brains: false, xp: 20, level: 1 },
  "treeAutumn2": { cost: 2, brains: true, xp: 0, level: 1 },
  "treeAutumn3": { cost: 2, brains: true, xp: 0, level: 1 },
  "treeFriendly": { cost: 300, brains: false, xp: 3, level: 1 },
  "treeHostile": { cost: 800, brains: false, xp: 8, level: 30 },
  "treeNeighborly": { cost: 500, brains: false, xp: 5, level: 10 },
  "treeSpooky": { cost: 0, brains: false, xp: 0, level: -1 },
  "treeWorldCobraHawk": { cost: 0, brains: false, xp: 0, level: -1 },
  "treeWorldMossCrab": { cost: 0, brains: false, xp: 0, level: -1 },
  "treeWorldPhoenix": { cost: 0, brains: false, xp: 0, level: -1 },
  "treeWorldPigling": { cost: 0, brains: false, xp: 0, level: -1 },
  "treeWorldPoppyHouse": { cost: 0, brains: false, xp: 0, level: -1 },
  "treehouse": { cost: 3, brains: true, xp: 300, level: 43 },
  "trojanHorse": { cost: 3, brains: true, xp: 0, level: 5 },
  "umbrellaOrange": { cost: 1, brains: true, xp: 0, level: 1 },
  "umbrellaYellow": { cost: 1, brains: true, xp: 0, level: 1 },
  "underwaterCoral": { cost: 1000, brains: false, xp: 10, level: 21 },
  "underwaterMermaid": { cost: 3, brains: true, xp: 0, level: 25 },
  "underwaterShip": { cost: 8, brains: true, xp: 0, level: 29 },
  "underwaterTreasure": { cost: 5000, brains: false, xp: 50, level: 27 },
  "urn": { cost: 3000, brains: false, xp: 30, level: 1 },
  "well": { cost: 10000, brains: false, xp: 100, level: 33 },
  "willowTree": { cost: 9300, brains: false, xp: 59, level: 23 },
  "windmill": { cost: 0, brains: false, xp: 0, level: -1 },
  "winterSnowWoman": { cost: 2, brains: true, xp: 0, level: 1 },
  "witchsCauldron": { cost: 0, brains: false, xp: 0, level: -1 },
  "xmasArch": { cost: 1, brains: true, xp: 500, level: 1 },
  "xmasCandle": { cost: 3000, brains: false, xp: 30, level: 1 },
  "xmasFence": { cost: 5000, brains: false, xp: 50, level: 1 },
  "xmasGifts": { cost: 2000, brains: false, xp: 20, level: 1 },
  "xmasGingerbreadHouse": { cost: 5, brains: true, xp: 0, level: 1 },
  "xmasTree": { cost: 3, brains: true, xp: 1500, level: -1 },
  "xmasWreath": { cost: 1500, brains: false, xp: 15, level: 1 },
  "yellowGift": { cost: 0, brains: false, xp: 0, level: -1 },
  "yellowSatchet": { cost: 1, brains: true, xp: 0, level: 1 },
  "zenGarden": { cost: 2, brains: true, xp: 300, level: 44 },
  "zombieCombiner": { cost: 500, brains: false, xp: 5, level: 3, purchaseLimit: 3 },
  "zombieGift": { cost: 5, brains: true, xp: 0, level: -1 },
  "zombieTopiaryNormal": { cost: 1750, brains: false, xp: 18, level: 15 },
  "zombieXingSign": { cost: 1, brains: true, xp: 500, level: 15 },
  // #endregion generated:OBJECTS
};

export function objectEcon(key: string): ObjectEcon | undefined {
  return Object.prototype.hasOwnProperty.call(OBJECTS, key) ? OBJECTS[key] : undefined;
}

/** Gold paid when selling a placeable. Brain costs convert at 1,000 gold each;
 * gold costs use the normal ratio. Server-owned free rewards retain the game's
 * one-gold minimum; they cannot be bought, so this is not a buy/refund mint. */
export function objectRefund(cost: number, brains = false): number {
  if (brains) return Math.max(0, Math.trunc(cost)) * BRAIN_SELL_GOLD_RATE;
  return Math.max(1, Math.floor(cost * SELL_BACK_RATIO));
}

/** Gold paid for selling ONE placeable of `key`, priced the way the client prices it.
 *
 *  An award-only invasion prize was never bought, so it has no `cost` to take a
 *  fraction of and `objectRefund` floors it at one gold. Those carry an authored
 *  value instead (src/raidDropValue.ts — the single definition both sides read).
 *  `purchaseCost` is the price actually paid where the object records one (the Zombie
 *  Pot's dual pricing); it always wins, since a bought object is not an award. */
export function objectSellGold(
  key: string,
  econ: ObjectEcon,
  purchaseCost?: number | null,
  boughtWithBrains = econ.brains
): number {
  if (purchaseCost == null) {
    const awarded = awardedSellValue(key);
    if (awarded !== undefined) return awarded;
  }
  return objectRefund(purchaseCost ?? econ.cost, boughtWithBrains);
}

/** XP granted for buying a placeable. Binary ground truth
 * (`+[MarketDataManager xpFromItem:]`): decor/tree purchases grant binary-era
 * cost*10 and functional/special purchases grant binary-era cost*8. Reforged
 * divided brain prices by ten when undoing brainflation, so current-price
 * equivalents are cost*100 and cost*80. Gold purchases retain positive authored
 * Market XP, falling back to floor(cost / 100) when it is missing. `brains` is
 * explicit because the Zombie Pot changes from a first gold purchase to subsequent
 * brain purchases at runtime. */
export function objectBuyXp(
  cost: number,
  sourceXp: number,
  brains = false,
  functional = false
): number {
  if (brains) return Math.max(0, Math.trunc(cost)) * (functional ? 80 : 100);
  const authoredXp = Math.max(0, sourceXp);
  return authoredXp > 0 ? authoredXp : Math.floor(Math.max(0, cost) / 100);
}

/** Per-key ownership ceiling — a plausibility bound (matches the save object cap). */
export const MAX_OBJECT_COUNT = 8192;

/** Item capacity of each storage shed (placeables.json `storageSlots`). The shed the
 *  account OWNS decides how many items its shed holds, so the cap is derived from
 *  object_counts rather than stored — an editable save can't declare it.
 *  KEEP IN SYNC with placeables.json. */
export const SHED_SLOTS: Readonly<Record<string, number>> = {
  // #region generated:SHED_SLOTS
  // Source: public/assets/placeables.json — regenerate with `npm run catalogs` (server/scripts/gen-catalogs.mjs) — do not hand-edit
  storage01: 8,
  storage02: 16,
  storage03: 24,
  storage04: 32,
  storage05: 40,
  storage06: 48,
  storage07: 56,
  storage08: 64,
  storage09: 72,
  // #endregion generated:SHED_SLOTS
};

/** The starter shed's capacity — what an account holds before buying a bigger one. Every
 *  farm starts with a Shabby Shed (free, so never server-tracked; see planObjectUpgrade). */
export const BASE_SHED_SLOTS = 8;
