// Server mirror of public/assets/placeables.json purchase economics. GENERATED —
// KEEP IN SYNC. Only the fields that decide VALUE are mirrored: buy cost + currency
// + source xp. The server prices a placeable BUY and REFUND from THIS table (never a
// client amount): buy debits `cost` (brains if `brains`, else gold) and grants buyXp;
// refund credits floor(cost * SELL_BACK_RATIO). Object ownership is tracked as a COUNT
// per key (like boosts) — placement/position stays client-side layout.
//
// NOTE: the Zombie Pot has dynamic client pricing (500 first / 30 after) and stays a
// client-side purchase; it is still listed here for completeness but the client does
// not route its buy/refund through the server.

export const SELL_BACK_RATIO = 0.2; // mirrors src/economy.ts ECONOMY.SELL_BACK_RATIO
export const BUY_XP_COST_FRACTION = 0.1; // mirrors src/economy.ts

export interface ObjectEcon {
  cost: number;
  brains: boolean; // cost paid in brains, not gold
  xp: number;      // source xp (0 => buyXp falls back to a fraction of cost)
  /** Player level required to buy. -1 means NO requirement (59 seasonal/promo items),
   *  matching the client's `state.level < def.level` check, which -1 passes for free. */
  level: number;
}

export const OBJECTS: Readonly<Record<string, ObjectEcon>> = {
  "alienBanner": { cost: 0, brains: false, xp: 0, level: -1 },
  "baloon": { cost: 900, brains: false, xp: 9, level: 21 },
  "bambooTree": { cost: 11300, brains: false, xp: 75, level: 26 },
  "barbWireFence_01": { cost: 500, brains: false, xp: 5, level: 8 },
  "barrelNormal": { cost: 400, brains: false, xp: 4, level: 4 },
  "barrelOfFireworks": { cost: 10000, brains: false, xp: 0, level: 1 },
  "bbqGrill": { cost: 10, brains: true, xp: 0, level: 1 },
  "beachBall": { cost: 10, brains: true, xp: 0, level: 1 },
  "beechTree": { cost: 4500, brains: false, xp: 33, level: 15 },
  "bigEasterEggBlue": { cost: 10, brains: true, xp: 0, level: 1 },
  "bigEasterEggGreen": { cost: 10, brains: true, xp: 0, level: 1 },
  "bigEasterEggPink": { cost: 10, brains: true, xp: 0, level: 1 },
  "bike": { cost: 20, brains: true, xp: 1000, level: 36 },
  "birdhouse": { cost: 10000, brains: false, xp: 100, level: 41 },
  "birthdayCakeThirdYearRight": { cost: 10, brains: false, xp: 0, level: 1 },
  "bonfire": { cost: 2000, brains: false, xp: 20, level: 13 },
  "boxoLantern": { cost: 50, brains: true, xp: 0, level: -1 },
  "brokenTractor": { cost: 0, brains: false, xp: 0, level: -1 },
  "brokenWagon": { cost: 15000, brains: false, xp: 150, level: 41 },
  "bullseye": { cost: 5000, brains: false, xp: 50, level: 42 },
  "bunchOfCandles": { cost: 3000, brains: false, xp: 30, level: 8 },
  "butterChurn": { cost: 5000, brains: false, xp: 0, level: 37 },
  "cameraNormal": { cost: 10, brains: true, xp: 100, level: 1 },
  "candle": { cost: 1000, brains: false, xp: 10, level: 4 },
  "cannon": { cost: 20, brains: true, xp: 0, level: 1 },
  "cannonBalls": { cost: 5000, brains: false, xp: 0, level: 1 },
  "carecrowNormal": { cost: 20000, brains: false, xp: 200, level: 19 },
  "cemeteryFence_01": { cost: 900, brains: false, xp: 9, level: 23 },
  "chocolateTile": { cost: 3000, brains: false, xp: 30, level: 26 },
  "circusFlagBlue": { cost: 0, brains: false, xp: 0, level: -1 },
  "circusFlagGreen": { cost: 0, brains: false, xp: 0, level: -1 },
  "circusFlagYellow": { cost: 0, brains: false, xp: 0, level: -1 },
  "circusPopcorn": { cost: 0, brains: false, xp: 0, level: -1 },
  "circusTent": { cost: 0, brains: false, xp: 0, level: -1 },
  "cityLamp": { cost: 1800, brains: false, xp: 18, level: 24 },
  "cobblestoneRoadBend_01": { cost: 1500, brains: false, xp: 15, level: 20 },
  "cobblestoneRoadIntersection": { cost: 1500, brains: false, xp: 15, level: 20 },
  "cobblestoneRoadStraight_01": { cost: 1500, brains: false, xp: 15, level: 20 },
  "coconutTree": { cost: 2300, brains: false, xp: 23, level: 9 },
  "coffin1": { cost: 0, brains: false, xp: 0, level: -1 },
  "coffin2": { cost: 0, brains: false, xp: 0, level: -1 },
  "coffin3": { cost: 0, brains: false, xp: 0, level: -1 },
  "coolerLarge": { cost: 6000, brains: false, xp: 0, level: 14 },
  "coolerSmall": { cost: 5000, brains: false, xp: 0, level: 11 },
  "corporatevilleBanner": { cost: 0, brains: false, xp: 0, level: -1 },
  "cottonCandyTree": { cost: 1500, brains: false, xp: 15, level: 7 },
  "crashedUFO": { cost: 0, brains: false, xp: 0, level: -1 },
  "crate": { cost: 500, brains: false, xp: 5, level: 22 },
  "croquet": { cost: 10000, brains: false, xp: 100, level: 42 },
  "cursedChest": { cost: 20, brains: true, xp: 0, level: 1 },
  "cypressTree": { cost: 500, brains: false, xp: 5, level: 3 },
  "daisy": { cost: 10, brains: false, xp: 0, level: 6 },
  "desertSkull": { cost: 3000, brains: false, xp: 30, level: 26 },
  "doubleRainbow_01": { cost: 20, brains: true, xp: 1000, level: 26 },
  "drgroundhogBurrow": { cost: 40, brains: true, xp: 0, level: 25 },
  "drgroundhogDistillery": { cost: 20, brains: true, xp: 0, level: 25 },
  "drgroundhogEvilDevice": { cost: 10, brains: true, xp: 0, level: 25 },
  "drgroundhogEvilLab": { cost: 40, brains: true, xp: 0, level: 25 },
  "drgroundhogLabShelves": { cost: 10, brains: true, xp: 0, level: 25 },
  "drgroundhogLabTable": { cost: 10, brains: true, xp: 0, level: 25 },
  "drgroundhogNutStash": { cost: 10, brains: true, xp: 0, level: 25 },
  "drgroundhogTricycle": { cost: 10, brains: true, xp: 0, level: 25 },
  "drinksCooler": { cost: 10, brains: true, xp: 0, level: 1 },
  "easterBasket": { cost: 20, brains: true, xp: 0, level: 1 },
  "easterEggBlue": { cost: 500, brains: false, xp: 0, level: 1 },
  "easterEggGreen": { cost: 500, brains: false, xp: 0, level: 1 },
  "easterEggPink": { cost: 500, brains: false, xp: 0, level: 1 },
  "easterEggPurple": { cost: 500, brains: false, xp: 0, level: 1 },
  "easterEggWhite": { cost: 400, brains: false, xp: 0, level: 1 },
  "easterGrass": { cost: 1500, brains: false, xp: 0, level: 1 },
  "eggBush": { cost: 10, brains: true, xp: 0, level: 1 },
  "eggLamp": { cost: 30, brains: true, xp: 0, level: 1 },
  "evergreenTree": { cost: 11300, brains: false, xp: 113, level: 32 },
  "fancyFireplace": { cost: 30, brains: true, xp: 0, level: 1 },
  "fenceGate_01_closed": { cost: 500, brains: false, xp: 5, level: 2 },
  "fenceGate_01_open": { cost: 500, brains: false, xp: 5, level: 2 },
  "fireflies": { cost: 10, brains: true, xp: 0, level: 25 },
  "fireRing": { cost: 0, brains: false, xp: 0, level: -1 },
  "flowerBed": { cost: 200, brains: false, xp: 2, level: 9 },
  "fountain": { cost: 10, brains: true, xp: 500, level: 16 },
  "fruitTreeApple": { cost: 500, brains: false, xp: 0, level: 1 },
  "fruitTreeLemon": { cost: 2000, brains: false, xp: 0, level: 10 },
  "fruitTreeOrange": { cost: 1000, brains: false, xp: 0, level: 15 },
  "gallows": { cost: 20, brains: true, xp: 1000, level: 21 },
  "gazeboNormal": { cost: 100000, brains: false, xp: 1000, level: 20 },
  "geyser": { cost: 30, brains: true, xp: 0, level: 34 },
  "giantCandyCane": { cost: 10, brains: true, xp: 500, level: 26 },
  "giantClamClosed": { cost: 0, brains: false, xp: 0, level: -1 },
  "gibbetCage": { cost: 30, brains: true, xp: 0, level: 1 },
  "glowFlowerDay": { cost: 500, brains: false, xp: 0, level: 20 },
  "glowMushroomDay": { cost: 400, brains: false, xp: 0, level: 10 },
  "glowSkullDay": { cost: 500, brains: false, xp: 0, level: 30 },
  "glowStoneDay": { cost: 250, brains: false, xp: 0, level: 1 },
  "gnomeStatue": { cost: 20, brains: true, xp: 200, level: 44 },
  "goldEgg": { cost: 50, brains: true, xp: 0, level: 1 },
  "grainSilo": { cost: 4500, brains: false, xp: 0, level: 33 },
  "graveAngel": { cost: 1000, brains: false, xp: 0, level: 20 },
  "graveFlat": { cost: 500, brains: false, xp: 0, level: 1 },
  "graveGargoyle": { cost: 1000, brains: false, xp: 0, level: 30 },
  "graveOld": { cost: 800, brains: false, xp: 0, level: 10 },
  "gravestoneBlue": { cost: 20, brains: true, xp: 400, level: 1 },
  "gravestoneRed": { cost: 40, brains: true, xp: 400, level: 15 },
  "gravestoneRound": { cost: 800, brains: false, xp: 8, level: 5 },
  "gravestoneSilver": { cost: 60, brains: true, xp: 400, level: 25 },
  "greenGift": { cost: 0, brains: false, xp: 0, level: -1 },
  "hauntedClocktower": { cost: 0, brains: false, xp: 0, level: -1 },
  "haystack": { cost: 2500, brains: false, xp: 25, level: 11 },
  "hazardFence": { cost: 0, brains: false, xp: 0, level: -1 },
  "heartCandle": { cost: 0, brains: false, xp: 0, level: -1 },
  "heartFountain": { cost: 100, brains: true, xp: 6000, level: 1 },
  "heartHedge": { cost: 0, brains: false, xp: 0, level: -1 },
  "hedge_01": { cost: 1000, brains: false, xp: 10, level: 7 },
  "holidayChocolateFountain": { cost: 100, brains: true, xp: 0, level: 1 },
  "hotdogCart": { cost: 10000, brains: false, xp: 100, level: 45 },
  "iceCreamConeChocolate": { cost: 0, brains: false, xp: 0, level: -1 },
  "iceCreamConeStrawberry": { cost: 0, brains: false, xp: 0, level: -1 },
  "iceCreamConeVanilla": { cost: 0, brains: false, xp: 0, level: -1 },
  "iceCreamStand": { cost: 0, brains: false, xp: 0, level: -1 },
  "iceCreamTruck": { cost: 0, brains: false, xp: 0, level: -1 },
  "ironGate_01_closed": { cost: 1800, brains: false, xp: 18, level: 23 },
  "ironGate_01_open": { cost: 1800, brains: false, xp: 18, level: 23 },
  "islandRelic": { cost: 20000, brains: false, xp: 0, level: 1 },
  "koiPond": { cost: 50, brains: true, xp: 500, level: 44 },
  "lawnmower": { cost: 7000, brains: false, xp: 70, level: 45 },
  "leafPile": { cost: 10, brains: false, xp: 0, level: 11 },
  "lemonadeStand": { cost: 9000, brains: false, xp: 0, level: 38 },
  "libertyBell": { cost: 50, brains: true, xp: 0, level: 1 },
  "libertyMonument": { cost: 100000, brains: false, xp: 0, level: 1 },
  "libertySnareDrum": { cost: 20, brains: true, xp: 0, level: 1 },
  "lifeguardChair": { cost: 30, brains: true, xp: 0, level: 1 },
  "logCabin": { cost: 40, brains: true, xp: 2000, level: 36 },
  "lollipop": { cost: 1500, brains: false, xp: 15, level: 21 },
  "loveShack": { cost: 0, brains: false, xp: 0, level: -1 },
  "mailboxNormal": { cost: 950, brains: false, xp: 9, level: 8 },
  "mausoleum3": { cost: 80, brains: true, xp: 300, level: 1 },
  "mechanicalBull": { cost: 0, brains: false, xp: 0, level: -1 },
  "monkeyBars": { cost: 4000, brains: false, xp: 0, level: 40 },
  "monolithCombine": { cost: 120, brains: true, xp: 6000, level: 25 },
  "monolithMutation": { cost: 80, brains: true, xp: 800, level: 1 },
  "monolithPlowing": { cost: 100, brains: true, xp: 1000, level: 1 },
  "monolithSpeed": { cost: 100, brains: true, xp: 1000, level: 1 },
  "monolithZombie": { cost: 100, brains: true, xp: 1000, level: 1 },
  "monument": { cost: 0, brains: false, xp: 0, level: -1 },
  "ninjaBanner": { cost: 0, brains: false, xp: 0, level: -1 },
  "oakTree": { cost: 900, brains: false, xp: 9, level: 5 },
  "oldMcDonnellBanner": { cost: 0, brains: false, xp: 0, level: -1 },
  "oliveTreeOlive": { cost: 1000, brains: false, xp: 0, level: 1 },
  "olympus": { cost: 50, brains: true, xp: 500, level: 44 },
  "outhouseNormal": { cost: 2250, brains: false, xp: 22, level: 13 },
  "pailAndShovel": { cost: 4000, brains: false, xp: 0, level: 1 },
  "palmTree": { cost: 15900, brains: false, xp: 93, level: 29 },
  "parrot": { cost: 0, brains: false, xp: 0, level: -1 },
  "peepPink": { cost: 800, brains: false, xp: 0, level: 1 },
  "peepYellow": { cost: 800, brains: false, xp: 0, level: 1 },
  "pen_01": { cost: 250, brains: false, xp: 2, level: 2 },
  "picnicNormal": { cost: 4000, brains: false, xp: 40, level: 17 },
  "pirateBag": { cost: 2000, brains: false, xp: 0, level: 1 },
  "pirateBanner": { cost: 0, brains: false, xp: 0, level: -1 },
  "pirateBarrel": { cost: 10000, brains: false, xp: 0, level: 1 },
  "pirateCrate": { cost: 10, brains: true, xp: 0, level: 1 },
  "pirateCratePlain": { cost: 2000, brains: false, xp: 0, level: 1 },
  "pirateSack": { cost: 2000, brains: false, xp: 0, level: 1 },
  "pixelBanner": { cost: 0, brains: false, xp: 0, level: -1 },
  "pixelBrick": { cost: 0, brains: false, xp: 0, level: -1 },
  "pixelBrickFloating": { cost: 0, brains: false, xp: 0, level: -1 },
  "pixelCampfire": { cost: 0, brains: false, xp: 0, level: -1 },
  "pixelTower": { cost: 0, brains: false, xp: 0, level: -1 },
  "pixelTree": { cost: 0, brains: false, xp: 0, level: -1 },
  "postalMailBox": { cost: 3000, brains: false, xp: 0, level: 40 },
  "powderKeg": { cost: 10, brains: true, xp: 0, level: 1 },
  "pumpkinAngry": { cost: 9000, brains: false, xp: 90, level: 31 },
  "pumpkinHappy": { cost: 9000, brains: false, xp: 90, level: 29 },
  "pumpkinMan": { cost: 30, brains: true, xp: 1500, level: 31 },
  "pyramid": { cost: 200000, brains: false, xp: 2000, level: 35 },
  "redGift": { cost: 0, brains: false, xp: 0, level: -1 },
  "roadBend_01": { cost: 800, brains: false, xp: 8, level: 8 },
  "roadIntersection": { cost: 850, brains: false, xp: 8, level: 8 },
  "roadStraight": { cost: 750, brains: false, xp: 7, level: 8 },
  "robotBanner": { cost: 0, brains: false, xp: 0, level: -1 },
  "rockBunny": { cost: 0, brains: false, xp: 0, level: -1 },
  "rockLobster": { cost: 0, brains: false, xp: 0, level: -1 },
  "rocks": { cost: 50, brains: false, xp: 0, level: 12 },
  "rope": { cost: 2000, brains: false, xp: 0, level: 1 },
  "rubberTree": { cost: 7500, brains: false, xp: 45, level: 20 },
  "rumBarrel": { cost: 2000, brains: false, xp: 0, level: 1 },
  "sandCastle": { cost: 50, brains: true, xp: 0, level: 1 },
  "sandDollar": { cost: 0, brains: false, xp: 0, level: -1 },
  "scarecrowNormal": { cost: 12000, brains: false, xp: 120, level: 18 },
  "sculptureOfLiberty": { cost: 50, brains: true, xp: 0, level: 1 },
  "setiDish": { cost: 0, brains: false, xp: 0, level: -1 },
  "shamrocks": { cost: 10, brains: false, xp: 0, level: 7 },
  "shellScallop": { cost: 50, brains: false, xp: 0, level: 3 },
  "shellTrumpet": { cost: 75, brains: false, xp: 0, level: 6 },
  "shipWheel": { cost: 15, brains: true, xp: 0, level: 1 },
  "skeletonCouple": { cost: 30, brains: true, xp: 0, level: -1 },
  "skullCandle": { cost: 4500, brains: false, xp: 45, level: 28 },
  "skullWithSnake": { cost: 4000, brains: false, xp: 40, level: 27 },
  "smallCactus": { cost: 3300, brains: false, xp: 7, level: 12 },
  "snowHedge_01": { cost: 5000, brains: false, xp: 50, level: 30 },
  "soil_zombiePatch": { cost: 30, brains: true, xp: 300, level: 1 },
  "spaceSolarSystem": { cost: 50, brains: true, xp: 0, level: 1 },
  "spaceWormHoleA": { cost: 30, brains: true, xp: 0, level: 1 },
  "spaceWormHoleB": { cost: 30, brains: true, xp: 0, level: 1 },
  "squirmyWorms": { cost: 10, brains: true, xp: 0, level: 25 },
  "starfish": { cost: 50, brains: false, xp: 0, level: 9 },
  "starTopiary": { cost: 3000, brains: false, xp: 0, level: 1 },
  "storage01": { cost: 0, brains: false, xp: 0, level: 1 },
  "storage02": { cost: 15000, brains: false, xp: 150, level: 1 },
  "storage03": { cost: 30000, brains: false, xp: 300, level: 1 },
  "storage04": { cost: 60000, brains: false, xp: 600, level: 1 },
  "storage05": { cost: 95000, brains: false, xp: 950, level: 1 },
  "storage06": { cost: 145000, brains: false, xp: 1450, level: 1 },
  "storage07": { cost: 225000, brains: false, xp: 2250, level: 1 },
  "storage08": { cost: 350000, brains: false, xp: 3500, level: 1 },
  "stPatricksFountain": { cost: 50, brains: true, xp: 0, level: 1 },
  "stPatricksIrishFlag": { cost: 10000, brains: false, xp: 0, level: 1 },
  "streetLight": { cost: 3000, brains: false, xp: 30, level: 28 },
  "sundial": { cost: 20, brains: true, xp: 0, level: 37 },
  "surfboardBlue": { cost: 10, brains: true, xp: 0, level: 1 },
  "surfboardRed": { cost: 20, brains: true, xp: 0, level: 1 },
  "swingSet": { cost: 10000, brains: false, xp: 0, level: 39 },
  "taikoDrum": { cost: 0, brains: false, xp: 0, level: -1 },
  "tallCactus": { cost: 10, brains: true, xp: 500, level: 18 },
  "teddyBear": { cost: 0, brains: false, xp: 0, level: -1 },
  "teddyValentine": { cost: 0, brains: false, xp: 0, level: -1 },
  "telephonePole": { cost: 2200, brains: false, xp: 22, level: 27 },
  "tentNormal": { cost: 10, brains: true, xp: 500, level: 1 },
  "tikiHeadLarge": { cost: 15, brains: true, xp: 0, level: 1 },
  "tikiHeadSmall": { cost: 20, brains: true, xp: 0, level: 1 },
  "tikiTorch": { cost: 10, brains: true, xp: 0, level: 29 },
  "totemPole": { cost: 10, brains: true, xp: 500, level: 8 },
  "toxicDrum": { cost: 0, brains: false, xp: 0, level: -1 },
  "treasureChest": { cost: 10, brains: true, xp: 500, level: 21 },
  "treeAmiable": { cost: 800, brains: false, xp: 0, level: 20 },
  "treeFriendly": { cost: 300, brains: false, xp: 0, level: 1 },
  "treeHostile": { cost: 800, brains: false, xp: 0, level: 30 },
  "treehouse": { cost: 30, brains: true, xp: 300, level: 43 },
  "treeNeighborly": { cost: 500, brains: false, xp: 0, level: 10 },
  "treeSpooky": { cost: 0, brains: false, xp: 0, level: -1 },
  "treeWorldCobraHawk": { cost: 0, brains: false, xp: 0, level: -1 },
  "treeWorldMossCrab": { cost: 0, brains: false, xp: 0, level: -1 },
  "treeWorldPhoenix": { cost: 0, brains: false, xp: 0, level: -1 },
  "treeWorldPigling": { cost: 0, brains: false, xp: 0, level: -1 },
  "treeWorldPoppyHouse": { cost: 0, brains: false, xp: 0, level: -1 },
  "umbrellaOrange": { cost: 10, brains: true, xp: 0, level: 1 },
  "umbrellaYellow": { cost: 10, brains: true, xp: 0, level: 1 },
  "well": { cost: 10000, brains: false, xp: 0, level: 33 },
  "willowTree": { cost: 9300, brains: false, xp: 59, level: 23 },
  "windmill": { cost: 0, brains: false, xp: 0, level: -1 },
  "witchsCauldron": { cost: 0, brains: false, xp: 0, level: -1 },
  "yellowGift": { cost: 0, brains: false, xp: 0, level: -1 },
  "zenGarden": { cost: 20, brains: true, xp: 300, level: 44 },
  "zombieCombiner": { cost: 500, brains: false, xp: 500, level: 3 },
  "zombieGift": { cost: 50, brains: true, xp: 0, level: -1 },
  "zombieTopiaryNormal": { cost: 1750, brains: false, xp: 18, level: 15 },
  "zombieXingSign": { cost: 10, brains: true, xp: 500, level: 15 },
};

export function objectEcon(key: string): ObjectEcon | undefined {
  return Object.prototype.hasOwnProperty.call(OBJECTS, key) ? OBJECTS[key] : undefined;
}

/** Gold/brains refunded when selling a placeable bought for `cost` (min 1). A free
 *  (cost 0) placeable refunds NOTHING — otherwise buy-free → refund-1 would mint. */
export function objectRefund(cost: number): number {
  return cost > 0 ? Math.max(1, Math.floor(cost * SELL_BACK_RATIO)) : 0;
}

/** XP granted for buying a placeable: its source xp, else a fraction of cost (min 1). */
export function objectBuyXp(cost: number, sourceXp: number): number {
  if (sourceXp > 0) return sourceXp;
  return Math.max(1, Math.round(cost * BUY_XP_COST_FRACTION));
}

/** Per-key ownership ceiling — a plausibility bound (matches the save object cap). */
export const MAX_OBJECT_COUNT = 8192;
