// Freeze the effective-strength fit into source.
//
// The grid has to bin rosters at simulation time, and the fit lives in tmp/ as the output
// of a 9,000-flight run. Checking the numbers in makes the grid reproducible without
// re-running that, and makes a change to them show up in a diff like any other rule.
// Regenerate with: npm run test:effective && node tools/freeze_effective.mjs
import { readFileSync, writeFileSync } from "node:fs";

const fit = JSON.parse(readFileSync("tmp/effective/fit.json", "utf8"));

const byGroup = {};
for (const s of fit.species) (byGroup[s.group] ||= []).push(s);

const classMean = {};
const classMeanLadder = {};
for (const [g, xs] of Object.entries(byGroup)) {
  classMean[g] = xs.reduce((a, x) => a + x.effective, 0) / xs.length;
  classMeanLadder[g] = xs.reduce((a, x) => a + x.ladder, 0) / xs.length;
}
let sxy = 0, sxx = 0;
for (const [g, xs] of Object.entries(byGroup)) {
  for (const x of xs) {
    const dx = x.ladder - classMeanLadder[g];
    sxy += dx * (x.effective - classMean[g]);
    sxx += dx * dx;
  }
}
const slope = sxy / sxx;

const num = (v) => Number(v.toFixed(4));
const table = (o) => Object.entries(o).sort().map(([k, v]) => `  ${k}: ${num(v)},`).join("\n");

const out = `// GENERATED by tools/freeze_effective.mjs — do not edit by hand.
//
// The effective-strength fit, frozen. Regenerate with:
//   npm run test:effective && node tools/freeze_effective.mjs
//
// Measured over ${fit.parties} uniformly random sixteen-zombie armies flown against a
// six-fight battery at expert play (src/raid/harness/effectiveStrength.ts). On ${fit.validation.heldOut}
// held-out armies these weights order results at Spearman ${num(fit.validation.fittedSpearman)}, against the
// Strength Ladder's ${num(fit.validation.ladderSpearman)} — the old metric is not weak, it is
// ANTI-correlated with winning.
//
// Values are on the Strength Ladder's numeric range so the two can be read side by side.
// Only DIFFERENCES are meaningful: every army has sixteen slots, so the counts sum to a
// constant and a shared offset predicts identically.

/** Per-species, for the ${fit.species.length} species actually sampled (the level-50 shortlist). */
export const EFFECTIVE_WEIGHT: Readonly<Record<string, number>> = {
${fit.species.map((s) => `  ${s.key}: ${num(s.effective)}, // ${s.group} · ladder ${num(s.ladder)}`).join("\n")}
};

/** Mean effective value of a class, for species the sample never contained. */
export const CLASS_EFFECTIVE: Readonly<Record<string, number>> = {
${table(classMean)}
};

/** Mean Strength Ladder score of the sampled species of each class — the point the
 *  within-class slope below is measured RELATIVE TO. */
export const CLASS_LADDER: Readonly<Record<string, number>> = {
${table(classMeanLadder)}
};

/** One pooled within-class slope, effective points per Strength Ladder point.
 *
 *  Pooled rather than per class because three species per class cannot support six slopes.
 *  It is small — over the whole sampled ladder span it moves a species by about 7 points
 *  against a 6-point spread between class means — which is the finding restated: WHICH
 *  CLASS you field matters about as much as everything else put together. */
export const WITHIN_CLASS_SLOPE = ${num(slope)};

/** Provenance, so a number here can always be traced to the run that produced it. */
export const EFFECTIVE_FIT_META = {
  parties: ${fit.parties},
  heldOut: ${fit.validation.heldOut},
  fittedSpearman: ${num(fit.validation.fittedSpearman)},
  ladderSpearman: ${num(fit.validation.ladderSpearman)},
  sampledSpecies: ${fit.species.length},
} as const;
`;

writeFileSync("src/raid/harness/effectiveWeights.ts", out);
console.log(`wrote src/raid/harness/effectiveWeights.ts — ${fit.species.length} species, slope ${num(slope)}`);
