// Service-worker registration + auto-update UX for the installed/PWA build.
//
// The SW itself is generated by vite-plugin-pwa (see vite.config.ts) and only
// exists in a production build; in dev the virtual module's registerSW is a
// no-op, so importing this is harmless everywhere. We register MANUALLY (rather
// than the plugin's injected inline script) because the strict build CSP has no
// 'unsafe-inline' for scripts — this module is bundled, so it runs under
// script-src 'self'.
//
// registerType is "prompt": a new version never reloads on its own (a silent
// reload mid-raid would be awful). Instead we surface a small toast and let the
// player tap "Reload" when they're ready.
import { registerSW } from "virtual:pwa-register";
import { repairStaleArtCache } from "./artCacheRepair";
import type { PlayMode } from "./playMode";
import {
  activateWaitingWorker,
  checkRegistrationForUpdate,
  findWorkerToActivate,
  type UpdateCheckResult,
} from "./updateCheck";

/** Retained so a non-service-worker caller (the ruleset-skew check) can reuse the
 *  SW's activate-and-reload path when an update is genuinely waiting. Null in dev,
 *  in browsers without service workers, and before initPwa runs. */
let updateSW: ((reloadPage?: boolean) => Promise<void>) | null = null;
let reloadRequested = false;

/** Promote the waiting worker before reloading. Reloading before confirmed activation
 *  can serve the old precached shell again and create an apparent update loop. */
async function activateWaitingWorkerAndReload(): Promise<void> {
  if (reloadRequested) return;
  reloadRequested = true;

  let registration: ServiceWorkerRegistration | undefined;
  try {
    registration = await navigator.serviceWorker.getRegistration();
  } catch {
    showUpdateRetryToast("The update couldn't start. Check your connection, then try again.");
    return;
  }
  if (!registration) {
    // No service worker at all (dev, or a browser without them): nothing can serve a
    // stale shell, so a plain reload genuinely refetches.
    location.reload();
    return;
  }

  // Nothing waiting means LOOK for an update, never reload anyway — see
  // findWorkerToActivate for why a bare reload here loops the player forever.
  const found = await findWorkerToActivate(registration);
  if (!found.worker) {
    // Genuinely nothing newer to install. Reloading cannot fix a skew on its own, so
    // say what is true instead of bouncing the player through the same toast again.
    showUpdateRetryToast(found.reason === "error"
      ? "Couldn't reach the update server. Check your connection, then try again."
      : "The new version isn't published yet. Try again in a minute.");
    return;
  }
  const waiting = found.worker;

  const activated = await activateWaitingWorker(waiting, navigator.serviceWorker);
  if (activated) {
    location.reload();
    return;
  }

  showUpdateRetryToast(
    "The update is taking longer than expected. Keep the game open, then try again.",
  );
}

function showUpdateRetryToast(message: string): void {
  reloadRequested = false;
  showUpdateToast(message, () => void activateWaitingWorkerAndReload());
}

/** Wire up the service worker. Call once at startup. Safe to call in dev. */
export function initPwa(mode: PlayMode): void {
  // Before anything else, and independent of the service worker: evict art whose
  // cached copy is known to be broken. The runtime art cache is CacheFirst on stable
  // filenames, so a corrected asset otherwise never reaches an existing install.
  // Fire-and-forget — the textures it drops are re-fetched on first use.
  void repairStaleArtCache();

  // Skip where service workers aren't available (older browsers, some embedded
  // webviews) — the game runs fine without offline caching.
  if (typeof navigator === "undefined" || !("serviceWorker" in navigator)) return;

  updateSW = registerSW({
    onNeedRefresh() {
      if (reloadRequested) return;
      showUpdateToast("A new version is ready.", () => void activateWaitingWorkerAndReload());
    },
    onOfflineReady() {
      showBriefToast(mode === "local"
        ? "Local Farm app shell is cached. Viewed artwork is available offline."
        : "App installed. Online Farm still requires an internet connection.");
    },
  });
}

/** Settings' "Check for Updates" button: poll the network on demand instead of
 *  waiting for the browser's own periodic check. When something is waiting we show
 *  the same bottom toast the automatic path uses; the caller reports the other
 *  outcomes in the Settings panel. */
export async function checkForUpdate(): Promise<UpdateCheckResult> {
  if (typeof navigator === "undefined" || !("serviceWorker" in navigator)) return "unavailable";

  const result = await checkRegistrationForUpdate(() =>
    navigator.serviceWorker.getRegistration());
  if (result === "update-ready" && !reloadRequested) {
    showUpdateToast("A new version is ready.", () => void activateWaitingWorkerAndReload());
  }
  return result;
}

/** Ask the player to reload, for a reason OTHER than a waiting service worker —
 *  currently a raid-ruleset mismatch between this tab's JS and the live Worker.
 *
 *  Prefers the service worker's skip-waiting path when one is registered, because a
 *  plain reload can be served straight back out of the precache. Falls back to
 *  `location.reload()` in dev and wherever no SW exists. Never reloads on its own —
 *  a silent reload mid-raid would cost the player the fight. */
export function promptReload(message: string): void {
  showUpdateToast(message, () => {
    if (updateSW) void activateWaitingWorkerAndReload();
    else location.reload();
  });
}

// --- Minimal, dependency-free toast ----------------------------------------
// Styling is set via element.style (inline styles are allowed by the CSP's
// style-src 'unsafe-inline'); the click handler is attached with addEventListener
// (not an inline onclick), so nothing needs script 'unsafe-inline'.

function baseToast(): HTMLDivElement {
  const t = document.createElement("div");
  Object.assign(t.style, {
    position: "fixed",
    left: "50%",
    bottom: "calc(16px + env(safe-area-inset-bottom, 0px))",
    transform: "translateX(-50%)",
    zIndex: "100001", // above the sign-in gate (100000) and HUD
    display: "flex",
    alignItems: "center",
    gap: "12px",
    maxWidth: "min(92vw, 420px)",
    padding: "10px 14px",
    borderRadius: "12px",
    background: "rgba(20, 28, 18, 0.96)",
    color: "#f3ecd2",
    font: '600 14px/1.3 "Trebuchet MS", system-ui, sans-serif',
    boxShadow: "0 8px 24px rgba(0,0,0,.45)",
    border: "1px solid rgba(243,236,210,.25)",
  } as CSSStyleDeclaration);
  return t;
}

/** The update toast currently on screen, if any. A manual check races the SW's own
 *  onNeedRefresh (both fire for the same update), so the newest toast replaces the
 *  old one rather than stacking a second Reload button on top of it. */
let activeUpdateToast: HTMLDivElement | null = null;

function showUpdateToast(message: string, onReload: () => void): void {
  activeUpdateToast?.remove();
  const t = baseToast();
  activeUpdateToast = t;

  const label = document.createElement("span");
  label.textContent = message;
  label.style.flex = "1";
  label.setAttribute("aria-live", "polite");

  const reload = document.createElement("button");
  reload.textContent = "Reload";
  Object.assign(reload.style, {
    cursor: "pointer",
    padding: "6px 14px",
    borderRadius: "8px",
    border: "none",
    background: "linear-gradient(90deg, #c9550a, #f07a1e)",
    color: "#fff",
    font: '700 13px/1 "Trebuchet MS", system-ui, sans-serif',
  } as CSSStyleDeclaration);
  reload.addEventListener("click", () => {
    if (reload.disabled) return;
    reload.disabled = true;
    reload.textContent = "Updating…";
    reload.style.cursor = "wait";
    reload.style.opacity = "0.75";
    dismiss.disabled = true;
    dismiss.style.visibility = "hidden";
    label.textContent = "Installing update… The game will reload automatically.";
    onReload();
  });

  const dismiss = document.createElement("button");
  dismiss.textContent = "×"; // ×
  Object.assign(dismiss.style, {
    cursor: "pointer",
    background: "transparent",
    border: "none",
    color: "#f3ecd2",
    font: "700 18px/1 system-ui, sans-serif",
    opacity: "0.7",
  } as CSSStyleDeclaration);
  dismiss.setAttribute("aria-label", "Dismiss");
  dismiss.addEventListener("click", () => {
    if (activeUpdateToast === t) activeUpdateToast = null;
    t.remove();
  });

  t.append(label, reload, dismiss);
  document.body.appendChild(t);
}

function showBriefToast(text: string): void {
  const t = baseToast();
  t.textContent = text;
  document.body.appendChild(t);
  setTimeout(() => {
    t.style.transition = "opacity .4s ease";
    t.style.opacity = "0";
    setTimeout(() => t.remove(), 450);
  }, 2500);
}
