// Service-worker registration + auto-update UX for the installed/PWA build.
//
// The SW itself is generated by vite-plugin-pwa (see vite.config.ts) and only
// exists in a production build; in dev the virtual module's registerSW is a
// no-op, so importing this is harmless everywhere. We register MANUALLY (rather
// than the plugin's injected inline script) because the strict build CSP has no
// 'unsafe-inline' for scripts — this module is bundled, so it runs under
// script-src 'self'.
//
// registerType is "prompt": a new version never reloads on its own (a silent
// reload mid-raid would be awful). Instead we surface a small toast and let the
// player tap "Reload" when they're ready.
import { registerSW } from "virtual:pwa-register";

/** Wire up the service worker. Call once at startup. Safe to call in dev. */
export function initPwa(): void {
  // Skip where service workers aren't available (older browsers, some embedded
  // webviews) — the game runs fine without offline caching.
  if (typeof navigator === "undefined" || !("serviceWorker" in navigator)) return;

  const updateSW = registerSW({
    onNeedRefresh() {
      showUpdateToast(() => updateSW(true)); // updateSW(true) = skip waiting + reload
    },
    onOfflineReady() {
      showBriefToast("Ready to play offline");
    },
  });
}

// --- Minimal, dependency-free toast ----------------------------------------
// Styling is set via element.style (inline styles are allowed by the CSP's
// style-src 'unsafe-inline'); the click handler is attached with addEventListener
// (not an inline onclick), so nothing needs script 'unsafe-inline'.

function baseToast(): HTMLDivElement {
  const t = document.createElement("div");
  Object.assign(t.style, {
    position: "fixed",
    left: "50%",
    bottom: "calc(16px + env(safe-area-inset-bottom, 0px))",
    transform: "translateX(-50%)",
    zIndex: "100001", // above the sign-in gate (100000) and HUD
    display: "flex",
    alignItems: "center",
    gap: "12px",
    maxWidth: "min(92vw, 420px)",
    padding: "10px 14px",
    borderRadius: "12px",
    background: "rgba(20, 28, 18, 0.96)",
    color: "#f3ecd2",
    font: '600 14px/1.3 "Trebuchet MS", system-ui, sans-serif',
    boxShadow: "0 8px 24px rgba(0,0,0,.45)",
    border: "1px solid rgba(243,236,210,.25)",
  } as CSSStyleDeclaration);
  return t;
}

function showUpdateToast(onReload: () => void): void {
  const t = baseToast();

  const label = document.createElement("span");
  label.textContent = "A new version is ready.";
  label.style.flex = "1";

  const reload = document.createElement("button");
  reload.textContent = "Reload";
  Object.assign(reload.style, {
    cursor: "pointer",
    padding: "6px 14px",
    borderRadius: "8px",
    border: "none",
    background: "linear-gradient(90deg, #c9550a, #f07a1e)",
    color: "#fff",
    font: '700 13px/1 "Trebuchet MS", system-ui, sans-serif',
  } as CSSStyleDeclaration);
  reload.addEventListener("click", onReload);

  const dismiss = document.createElement("button");
  dismiss.textContent = "×"; // ×
  Object.assign(dismiss.style, {
    cursor: "pointer",
    background: "transparent",
    border: "none",
    color: "#f3ecd2",
    font: "700 18px/1 system-ui, sans-serif",
    opacity: "0.7",
  } as CSSStyleDeclaration);
  dismiss.setAttribute("aria-label", "Dismiss");
  dismiss.addEventListener("click", () => t.remove());

  t.append(label, reload, dismiss);
  document.body.appendChild(t);
}

function showBriefToast(text: string): void {
  const t = baseToast();
  t.textContent = text;
  document.body.appendChild(t);
  setTimeout(() => {
    t.style.transition = "opacity .4s ease";
    t.style.opacity = "0";
    setTimeout(() => t.remove(), 450);
  }, 2500);
}
